use Morph;
use Test::More;

plan(tests => 374);

test_hash('sequor+Verb+Dep', {
    '+Pres+Ind' => {
        '+1st+Sg+Pass' => ['sequor'],
        '+2nd+Sg+Pass' => ['sequeris', 'sequere'],
        '+3rd+Sg+Pass' => ['sequitur'],
        '+1st+Pl+Pass' => ['sequimur'],
        '+2nd+Pl+Pass' => ['sequimini'],
        '+3rd+Pl+Pass' => ['sequuntur'],
    },
    '+Pres+Subj' => {
        '+1st+Sg+Pass' => ['sequar'],
        '+2nd+Sg+Pass' => ['sequaris', 'sequare'],
        '+3rd+Sg+Pass' => ['sequatur'],
        '+1st+Pl+Pass' => ['sequamur'],
        '+2nd+Pl+Pass' => ['sequamini'],
        '+3rd+Pl+Pass' => ['sequantur'],
    },
    '+Impf+Ind' => {
        '+1st+Sg+Pass' => ['sequebar'],
        '+2nd+Sg+Pass' => ['sequebaris', 'sequebare'],
        '+3rd+Sg+Pass' => ['sequebatur'],
        '+1st+Pl+Pass' => ['sequebamur'],
        '+2nd+Pl+Pass' => ['sequebamini'],
        '+3rd+Pl+Pass' => ['sequebantur'],
    },
    '+Impf+Subj' => {
        '+1st+Sg+Pass' => ['sequerer'],
        '+2nd+Sg+Pass' => ['sequereris', 'sequerere'],
        '+3rd+Sg+Pass' => ['sequeretur'],
        '+1st+Pl+Pass' => ['sequeremur'],
        '+2nd+Pl+Pass' => ['sequeremini'],
        '+3rd+Pl+Pass' => ['sequerentur'],
    },
    '+Fut+Ind' => {
        '+1st+Sg+Pass' => ['sequar'],
        '+2nd+Sg+Pass' => ['sequeris', 'sequere'],
        '+3rd+Sg+Pass' => ['sequetur'],
        '+1st+Pl+Pass' => ['sequemur'],
        '+2nd+Pl+Pass' => ['sequemini'],
        '+3rd+Pl+Pass' => ['sequentur'],
    },
    '+Pres+Impv' => {
        '+2nd+Sg+Pass' => ['sequere'],
        '+2nd+Pl+Pass' => ['sequimini'],
    },
    '+Inf' => {
        '+Pres+Pass' => ['sequi'],
    },
    '+Part' => {
        '+Pres' => {
            '+Masc' => {
                '+Nom+Sg' => ['sequens'],
                '+Voc+Sg' => ['sequens'],
                '+Acc+Sg' => ['sequentem'],
                '+Gen+Sg' => ['sequentis'],
                '+Dat+Sg' => ['sequenti'],
                '+Abl+Sg' => ['sequenti', 'sequente'],

                '+Nom+Pl' => ['sequentes'],
                '+Voc+Pl' => ['sequentes'],
                '+Acc+Pl' => ['sequentes'],
                '+Gen+Pl' => ['sequentium'],
                '+Dat+Pl' => ['sequentibus'],
                '+Abl+Pl' => ['sequentibus'],
            },
            '+Fem' => {
                '+Nom+Sg' => ['sequens'],
                '+Voc+Sg' => ['sequens'],
                '+Acc+Sg' => ['sequentem'],
                '+Gen+Sg' => ['sequentis'],
                '+Dat+Sg' => ['sequenti'],
                '+Abl+Sg' => ['sequenti', 'sequente'],

                '+Nom+Pl' => ['sequentes'],
                '+Voc+Pl' => ['sequentes'],
                '+Acc+Pl' => ['sequentes'],
                '+Gen+Pl' => ['sequentium'],
                '+Dat+Pl' => ['sequentibus'],
                '+Abl+Pl' => ['sequentibus'],
            },
            '+Neut' => {
                '+Nom+Sg' => ['sequens'],
                '+Voc+Sg' => ['sequens'],
                '+Acc+Sg' => ['sequens'],
                '+Gen+Sg' => ['sequentis'],
                '+Dat+Sg' => ['sequenti'],
                '+Abl+Sg' => ['sequenti', 'sequente'],

                '+Nom+Pl' => ['sequentia'],
                '+Voc+Pl' => ['sequentia'],
                '+Acc+Pl' => ['sequentia'],
                '+Gen+Pl' => ['sequentium'],
                '+Dat+Pl' => ['sequentibus'],
                '+Abl+Pl' => ['sequentibus'],
            },
        },
        '+Perf' => {
            '+Masc' => {
                '+Nom+Sg' => ['secutus'],
                '+Voc+Sg' => ['secute'],
                '+Acc+Sg' => ['secutum'],
                '+Gen+Sg' => ['secuti'],
                '+Dat+Sg' => ['secuto'],
                '+Abl+Sg' => ['secuto'],

                '+Nom+Pl' => ['secuti'],
                '+Voc+Pl' => ['secuti'],
                '+Acc+Pl' => ['secutos'],
                '+Gen+Pl' => ['secutorum'],
                '+Dat+Pl' => ['secutis'],
                '+Abl+Pl' => ['secutis'],
            },
            '+Fem' => {
                '+Nom+Sg' => ['secuta'],
                '+Voc+Sg' => ['secuta'],
                '+Acc+Sg' => ['secutam'],
                '+Gen+Sg' => ['secutae'],
                '+Dat+Sg' => ['secutae'],
                '+Abl+Sg' => ['secuta'],

                '+Nom+Pl' => ['secutae'],
                '+Voc+Pl' => ['secutae'],
                '+Acc+Pl' => ['secutas'],
                '+Gen+Pl' => ['secutarum'],
                '+Dat+Pl' => ['secutis'],
                '+Abl+Pl' => ['secutis'],
            },
            '+Neut' => {
                '+Nom+Sg' => ['secutum'],
                '+Voc+Sg' => ['secutum'],
                '+Acc+Sg' => ['secutum'],
                '+Gen+Sg' => ['secuti'],
                '+Dat+Sg' => ['secuto'],
                '+Abl+Sg' => ['secuto'],

                '+Nom+Pl' => ['secuta'],
                '+Voc+Pl' => ['secuta'],
                '+Acc+Pl' => ['secuta'],
                '+Gen+Pl' => ['secutorum'],
                '+Dat+Pl' => ['secutis'],
                '+Abl+Pl' => ['secutis'],
            },
        },
        '+Fut' => {
            '+Masc' => {
                '+Nom+Sg' => ['secuturus'],
                '+Voc+Sg' => ['secuture'],
                '+Acc+Sg' => ['secuturum'],
                '+Gen+Sg' => ['secuturi'],
                '+Dat+Sg' => ['secuturo'],
                '+Abl+Sg' => ['secuturo'],

                '+Nom+Pl' => ['secuturi'],
                '+Voc+Pl' => ['secuturi'],
                '+Acc+Pl' => ['secuturos'],
                '+Gen+Pl' => ['secuturorum'],
                '+Dat+Pl' => ['secuturis'],
                '+Abl+Pl' => ['secuturis'],
            },
            '+Fem' => {
                '+Nom+Sg' => ['secutura'],
                '+Voc+Sg' => ['secutura'],
                '+Acc+Sg' => ['secuturam'],
                '+Gen+Sg' => ['secuturae'],
                '+Dat+Sg' => ['secuturae'],
                '+Abl+Sg' => ['secutura'],

                '+Nom+Pl' => ['secuturae'],
                '+Voc+Pl' => ['secuturae'],
                '+Acc+Pl' => ['secuturas'],
                '+Gen+Pl' => ['secuturarum'],
                '+Dat+Pl' => ['secuturis'],
                '+Abl+Pl' => ['secuturis'],
            },
            '+Neut' => {
                '+Nom+Sg' => ['secuturum'],
                '+Voc+Sg' => ['secuturum'],
                '+Acc+Sg' => ['secuturum'],
                '+Gen+Sg' => ['secuturi'],
                '+Dat+Sg' => ['secuturo'],
                '+Abl+Sg' => ['secuturo'],

                '+Nom+Pl' => ['secutura'],
                '+Voc+Pl' => ['secutura'],
                '+Acc+Pl' => ['secutura'],
                '+Gen+Pl' => ['secuturorum'],
                '+Dat+Pl' => ['secuturis'],
                '+Abl+Pl' => ['secuturis'],
            },
        },
    },
    '+Ger' => {
        '+Acc' => ['sequendum'],
        '+Gen' => ['sequendi'],
        '+Dat' => ['sequendo'],
        '+Abl' => ['sequendo'],
    },
    '+Gerv' => {
        '+Masc' => {
            '+Nom+Sg' => ['sequendus'],
            '+Voc+Sg' => ['sequende'],
            '+Acc+Sg' => ['sequendum'],
            '+Gen+Sg' => ['sequendi'],
            '+Dat+Sg' => ['sequendo'],
            '+Abl+Sg' => ['sequendo'],

            '+Nom+Pl' => ['sequendi'],
            '+Voc+Pl' => ['sequendi'],
            '+Acc+Pl' => ['sequendos'],
            '+Gen+Pl' => ['sequendorum'],
            '+Dat+Pl' => ['sequendis'],
            '+Abl+Pl' => ['sequendis'],
        },
        '+Fem' => {
            '+Nom+Sg' => ['sequenda'],
            '+Voc+Sg' => ['sequenda'],
            '+Acc+Sg' => ['sequendam'],
            '+Gen+Sg' => ['sequendae'],
            '+Dat+Sg' => ['sequendae'],
            '+Abl+Sg' => ['sequenda'],

            '+Nom+Pl' => ['sequendae'],
            '+Voc+Pl' => ['sequendae'],
            '+Acc+Pl' => ['sequendas'],
            '+Gen+Pl' => ['sequendarum'],
            '+Dat+Pl' => ['sequendis'],
            '+Abl+Pl' => ['sequendis'],
        },
        '+Neut' => {
            '+Nom+Sg' => ['sequendum'],
            '+Voc+Sg' => ['sequendum'],
            '+Acc+Sg' => ['sequendum'],
            '+Gen+Sg' => ['sequendi'],
            '+Dat+Sg' => ['sequendo'],
            '+Abl+Sg' => ['sequendo'],

            '+Nom+Pl' => ['sequenda'],
            '+Voc+Pl' => ['sequenda'],
            '+Acc+Pl' => ['sequenda'],
            '+Gen+Pl' => ['sequendorum'],
            '+Dat+Pl' => ['sequendis'],
            '+Abl+Pl' => ['sequendis'],
        },
    },
    '+SupI' => ['secutum'],
    '+SupII' => ['secutu'],
});
