#!/usr/bin/python

from morph import *
from TAP.Simple import *

plan(374)

test_hash('partior+Verb+Dep', {
    '+Pres+Ind': {
        '+1S+Pass': ['partior'],
        '+2S+Pass': ['partiris', 'partire'],
        '+3S+Pass': ['partitur'],
        '+1P+Pass': ['partimur'],
        '+2P+Pass': ['partimini'],
        '+3P+Pass': ['partiuntur'],
    },
    '+Pres+Subj': {
        '+1S+Pass': ['partiar'],
        '+2S+Pass': ['partiaris', 'partiare'],
        '+3S+Pass': ['partiatur'],
        '+1P+Pass': ['partiamur'],
        '+2P+Pass': ['partiamini'],
        '+3P+Pass': ['partiantur'],
    },
    '+Impf+Ind': {
        '+1S+Pass': ['partiebar'],
        '+2S+Pass': ['partiebaris', 'partiebare'],
        '+3S+Pass': ['partiebatur'],
        '+1P+Pass': ['partiebamur'],
        '+2P+Pass': ['partiebamini'],
        '+3P+Pass': ['partiebantur'],
    },
    '+Impf+Subj': {
        '+1S+Pass': ['partirer'],
        '+2S+Pass': ['partireris', 'partirere'],
        '+3S+Pass': ['partiretur'],
        '+1P+Pass': ['partiremur'],
        '+2P+Pass': ['partiremini'],
        '+3P+Pass': ['partirentur'],
    },
    '+Fut+Ind': {
        '+1S+Pass': ['partiar'],
        '+2S+Pass': ['partieris', 'partiere'],
        '+3S+Pass': ['partietur'],
        '+1P+Pass': ['partiemur'],
        '+2P+Pass': ['partiemini'],
        '+3P+Pass': ['partientur'],
    },
    '+Pres+Impv': {
        '+2S+Pass': ['partire'],
        '+2P+Pass': ['partimini'],
    },
    '+Inf': {
        '+Pres+Pass': ['partiri'],
    },
    '+Part': {
        '+Pres': {
            '+Masc': {
                '+Nom+Sg': ['partiens'],
                '+Voc+Sg': ['partiens'],
                '+Acc+Sg': ['partientem'],
                '+Gen+Sg': ['partientis'],
                '+Dat+Sg': ['partienti'],
                '+Abl+Sg': ['partienti', 'partiente'],

                '+Nom+Pl': ['partientes'],
                '+Voc+Pl': ['partientes'],
                '+Acc+Pl': ['partientes'],
                '+Gen+Pl': ['partientium'],
                '+Dat+Pl': ['partientibus'],
                '+Abl+Pl': ['partientibus'],
            },
            '+Fem': {
                '+Nom+Sg': ['partiens'],
                '+Voc+Sg': ['partiens'],
                '+Acc+Sg': ['partientem'],
                '+Gen+Sg': ['partientis'],
                '+Dat+Sg': ['partienti'],
                '+Abl+Sg': ['partienti', 'partiente'],

                '+Nom+Pl': ['partientes'],
                '+Voc+Pl': ['partientes'],
                '+Acc+Pl': ['partientes'],
                '+Gen+Pl': ['partientium'],
                '+Dat+Pl': ['partientibus'],
                '+Abl+Pl': ['partientibus'],
            },
            '+Neut': {
                '+Nom+Sg': ['partiens'],
                '+Voc+Sg': ['partiens'],
                '+Acc+Sg': ['partiens'],
                '+Gen+Sg': ['partientis'],
                '+Dat+Sg': ['partienti'],
                '+Abl+Sg': ['partienti', 'partiente'],

                '+Nom+Pl': ['partientia'],
                '+Voc+Pl': ['partientia'],
                '+Acc+Pl': ['partientia'],
                '+Gen+Pl': ['partientium'],
                '+Dat+Pl': ['partientibus'],
                '+Abl+Pl': ['partientibus'],
            },
        },
        '+Perf': {
            '+Masc': {
                '+Nom+Sg': ['partitus'],
                '+Voc+Sg': ['partite'],
                '+Acc+Sg': ['partitum'],
                '+Gen+Sg': ['partiti'],
                '+Dat+Sg': ['partito'],
                '+Abl+Sg': ['partito'],

                '+Nom+Pl': ['partiti'],
                '+Voc+Pl': ['partiti'],
                '+Acc+Pl': ['partitos'],
                '+Gen+Pl': ['partitorum'],
                '+Dat+Pl': ['partitis'],
                '+Abl+Pl': ['partitis'],
            },
            '+Fem': {
                '+Nom+Sg': ['partita'],
                '+Voc+Sg': ['partita'],
                '+Acc+Sg': ['partitam'],
                '+Gen+Sg': ['partitae'],
                '+Dat+Sg': ['partitae'],
                '+Abl+Sg': ['partita'],

                '+Nom+Pl': ['partitae'],
                '+Voc+Pl': ['partitae'],
                '+Acc+Pl': ['partitas'],
                '+Gen+Pl': ['partitarum'],
                '+Dat+Pl': ['partitis'],
                '+Abl+Pl': ['partitis'],
            },
            '+Neut': {
                '+Nom+Sg': ['partitum'],
                '+Voc+Sg': ['partitum'],
                '+Acc+Sg': ['partitum'],
                '+Gen+Sg': ['partiti'],
                '+Dat+Sg': ['partito'],
                '+Abl+Sg': ['partito'],

                '+Nom+Pl': ['partita'],
                '+Voc+Pl': ['partita'],
                '+Acc+Pl': ['partita'],
                '+Gen+Pl': ['partitorum'],
                '+Dat+Pl': ['partitis'],
                '+Abl+Pl': ['partitis'],
            },
        },
        '+Fut': {
            '+Masc': {
                '+Nom+Sg': ['partiturus'],
                '+Voc+Sg': ['partiture'],
                '+Acc+Sg': ['partiturum'],
                '+Gen+Sg': ['partituri'],
                '+Dat+Sg': ['partituro'],
                '+Abl+Sg': ['partituro'],

                '+Nom+Pl': ['partituri'],
                '+Voc+Pl': ['partituri'],
                '+Acc+Pl': ['partituros'],
                '+Gen+Pl': ['partiturorum'],
                '+Dat+Pl': ['partituris'],
                '+Abl+Pl': ['partituris'],
            },
            '+Fem': {
                '+Nom+Sg': ['partitura'],
                '+Voc+Sg': ['partitura'],
                '+Acc+Sg': ['partituram'],
                '+Gen+Sg': ['partiturae'],
                '+Dat+Sg': ['partiturae'],
                '+Abl+Sg': ['partitura'],

                '+Nom+Pl': ['partiturae'],
                '+Voc+Pl': ['partiturae'],
                '+Acc+Pl': ['partituras'],
                '+Gen+Pl': ['partiturarum'],
                '+Dat+Pl': ['partituris'],
                '+Abl+Pl': ['partituris'],
            },
            '+Neut': {
                '+Nom+Sg': ['partiturum'],
                '+Voc+Sg': ['partiturum'],
                '+Acc+Sg': ['partiturum'],
                '+Gen+Sg': ['partituri'],
                '+Dat+Sg': ['partituro'],
                '+Abl+Sg': ['partituro'],

                '+Nom+Pl': ['partitura'],
                '+Voc+Pl': ['partitura'],
                '+Acc+Pl': ['partitura'],
                '+Gen+Pl': ['partiturorum'],
                '+Dat+Pl': ['partituris'],
                '+Abl+Pl': ['partituris'],
            },
        },
    },
    '+Ger': {
        '+Acc': ['partiendum'],
        '+Gen': ['partiendi'],
        '+Dat': ['partiendo'],
        '+Abl': ['partiendo'],
    },
    '+Gerv': {
        '+Masc': {
            '+Nom+Sg': ['partiendus'],
            '+Voc+Sg': ['partiende'],
            '+Acc+Sg': ['partiendum'],
            '+Gen+Sg': ['partiendi'],
            '+Dat+Sg': ['partiendo'],
            '+Abl+Sg': ['partiendo'],

            '+Nom+Pl': ['partiendi'],
            '+Voc+Pl': ['partiendi'],
            '+Acc+Pl': ['partiendos'],
            '+Gen+Pl': ['partiendorum'],
            '+Dat+Pl': ['partiendis'],
            '+Abl+Pl': ['partiendis'],
        },
        '+Fem': {
            '+Nom+Sg': ['partienda'],
            '+Voc+Sg': ['partienda'],
            '+Acc+Sg': ['partiendam'],
            '+Gen+Sg': ['partiendae'],
            '+Dat+Sg': ['partiendae'],
            '+Abl+Sg': ['partienda'],

            '+Nom+Pl': ['partiendae'],
            '+Voc+Pl': ['partiendae'],
            '+Acc+Pl': ['partiendas'],
            '+Gen+Pl': ['partiendarum'],
            '+Dat+Pl': ['partiendis'],
            '+Abl+Pl': ['partiendis'],
        },
        '+Neut': {
            '+Nom+Sg': ['partiendum'],
            '+Voc+Sg': ['partiendum'],
            '+Acc+Sg': ['partiendum'],
            '+Gen+Sg': ['partiendi'],
            '+Dat+Sg': ['partiendo'],
            '+Abl+Sg': ['partiendo'],

            '+Nom+Pl': ['partienda'],
            '+Voc+Pl': ['partienda'],
            '+Acc+Pl': ['partienda'],
            '+Gen+Pl': ['partiendorum'],
            '+Dat+Pl': ['partiendis'],
            '+Abl+Pl': ['partiendis'],
        },
    },
    '+SupI': ['partitum'],
    '+SupII': ['partitu'],
})
diag("%d" % Morph.formcount)
