#!/usr/bin/python

from morph import *
from TAP.Simple import *

plan(208)

test_hash('rego+Verb', {
    '+Pres+Ind': {
        '+1S+Act': ['rego'],
        '+2S+Act': ['regis'],
        '+3S+Act': ['regit'],
        '+1P+Act': ['regimus'],
        '+2P+Act': ['regitis'],
        '+3P+Act': ['regunt'],
        '+1S+Pass': ['regor'],
        '+2S+Pass': ['regeris', 'regere'],
        '+3S+Pass': ['regitur'],
        '+1P+Pass': ['regimur'],
        '+2P+Pass': ['regimini'],
        '+3P+Pass': ['reguntur'],
    },
    '+Pres+Subj': {
        '+1S+Act': ['regam'],
        '+2S+Act': ['regas'],
        '+3S+Act': ['regat'],
        '+1P+Act': ['regamus'],
        '+2P+Act': ['regatis'],
        '+3P+Act': ['regant'],
        '+1S+Pass': ['regar'],
        '+2S+Pass': ['regaris', 'regare'],
        '+3S+Pass': ['regatur'],
        '+1P+Pass': ['regamur'],
        '+2P+Pass': ['regamini'],
        '+3P+Pass': ['regantur'],
    },
    '+Impf+Ind': {
        '+1S+Act': ['regebam'],
        '+2S+Act': ['regebas'],
        '+3S+Act': ['regebat'],
        '+1P+Act': ['regebamus'],
        '+2P+Act': ['regebatis'],
        '+3P+Act': ['regebant'],
        '+1S+Pass': ['regebar'],
        '+2S+Pass': ['regebaris', 'regebare'],
        '+3S+Pass': ['regebatur'],
        '+1P+Pass': ['regebamur'],
        '+2P+Pass': ['regebamini'],
        '+3P+Pass': ['regebantur'],
    },
    '+Impf+Subj': {
        '+1S+Act': ['regerem'],
        '+2S+Act': ['regeres'],
        '+3S+Act': ['regeret'],
        '+1P+Act': ['regeremus'],
        '+2P+Act': ['regeretis'],
        '+3P+Act': ['regerent'],
        '+1S+Pass': ['regerer'],
        '+2S+Pass': ['regereris', 'regerere'],
        '+3S+Pass': ['regeretur'],
        '+1P+Pass': ['regeremur'],
        '+2P+Pass': ['regeremini'],
        '+3P+Pass': ['regerentur'],
    },
    '+Fut+Ind': {
        '+1S+Act': ['regam'],
        '+2S+Act': ['reges'],
        '+3S+Act': ['reget'],
        '+1P+Act': ['regemus'],
        '+2P+Act': ['regetis'],
        '+3P+Act': ['regent'],
        '+1S+Pass': ['regar'],
        '+2S+Pass': ['regeris', 'regere'],
        '+3S+Pass': ['regetur'],
        '+1P+Pass': ['regemur'],
        '+2P+Pass': ['regemini'],
        '+3P+Pass': ['regentur'],
    },
    '+Perf+Ind': {
        '+1S+Act': ['rexi'],
        '+2S+Act': ['rexisti'],
        '+3S+Act': ['rexit'],
        '+1P+Act': ['reximus'],
        '+2P+Act': ['rexistis'],
        '+3P+Act': ['rexerunt', 'rexere'],
    },
    '+Perf+Subj': {
        '+1S+Act': ['rexerim'],
        '+2S+Act': ['rexeris'],
        '+3S+Act': ['rexerit'],
        '+1P+Act': ['rexerimus'],
        '+2P+Act': ['rexeritis'],
        '+3P+Act': ['rexerint'],
    },
    '+Pqp+Ind': {
        '+1S+Act': ['rexeram'],
        '+2S+Act': ['rexeras'],
        '+3S+Act': ['rexerat'],
        '+1P+Act': ['rexeramus'],
        '+2P+Act': ['rexeratis'],
        '+3P+Act': ['rexerant'],
    },
    '+Pqp+Subj': {
        '+1S+Act': ['rexissem'],
        '+2S+Act': ['rexisses'],
        '+3S+Act': ['rexisset'],
        '+1P+Act': ['rexissemus'],
        '+2P+Act': ['rexissetis'],
        '+3P+Act': ['rexissent'],
    },
    '+FutII+Ind': {
        '+1S+Act': ['rexero'],
        '+2S+Act': ['rexeris'],
        '+3S+Act': ['rexerit'],
        '+1P+Act': ['rexerimus'],
        '+2P+Act': ['rexeritis'],
        '+3P+Act': ['rexerint'],
    },
    '+Pres+Impv': {
        '+2S+Act' : ['rege'],
        '+2P+Act' : ['regite'],
        '+2S+Pass': ['regere'],
        '+2P+Pass': ['regimini'],
    },
    '+Fut+Impv': {
        '+2S+Act': ['regito'],
        '+3S+Act': ['regito'],
        '+2P+Act': ['regitote'],
        '+3P+Act': ['regunto'],
    },
    '+Inf': {
        '+Pres+Act': ['regere'],
        '+Pres+Pass': ['regi'],
        '+Perf+Act': ['rexisse'],
    }
})
