#!/usr/bin/python

from morph import *
from TAP.Simple import *

plan(236)

test_hash('amo+Verb', {
    '+Pres+Ind': {
        '+1S+Act': ['amo'],
        '+2S+Act': ['amas'],
        '+3S+Act': ['amat'],
        '+1P+Act': ['amamus'],
        '+2P+Act': ['amatis'],
        '+3P+Act': ['amant'],
        '+1S+Pass': ['amor'],
        '+2S+Pass': ['amaris', 'amare'],
        '+3S+Pass': ['amatur'],
        '+1P+Pass': ['amamur'],
        '+2P+Pass': ['amamini'],
        '+3P+Pass': ['amantur'],
    },
    '+Pres+Subj': {
        '+1S+Act': ['amem'],
        '+2S+Act': ['ames'],
        '+3S+Act': ['amet'],
        '+1P+Act': ['amemus'],
        '+2P+Act': ['ametis'],
        '+3P+Act': ['ament'],
        '+1S+Pass': ['amer'],
        '+2S+Pass': ['ameris', 'amere'],
        '+3S+Pass': ['ametur'],
        '+1P+Pass': ['amemur'],
        '+2P+Pass': ['amemini'],
        '+3P+Pass': ['amentur'],
    },
    '+Impf+Ind': {
        '+1S+Act': ['amabam'],
        '+2S+Act': ['amabas'],
        '+3S+Act': ['amabat'],
        '+1P+Act': ['amabamus'],
        '+2P+Act': ['amabatis'],
        '+3P+Act': ['amabant'],
        '+1S+Pass': ['amabar'],
        '+2S+Pass': ['amabaris', 'amabare'],
        '+3S+Pass': ['amabatur'],
        '+1P+Pass': ['amabamur'],
        '+2P+Pass': ['amabamini'],
        '+3P+Pass': ['amabantur'],
    },
    '+Impf+Subj': {
        '+1S+Act': ['amarem'],
        '+2S+Act': ['amares'],
        '+3S+Act': ['amaret'],
        '+1P+Act': ['amaremus'],
        '+2P+Act': ['amaretis'],
        '+3P+Act': ['amarent'],
        '+1S+Pass': ['amarer'],
        '+2S+Pass': ['amareris', 'amarere'],
        '+3S+Pass': ['amaretur'],
        '+1P+Pass': ['amaremur'],
        '+2P+Pass': ['amaremini'],
        '+3P+Pass': ['amarentur'],
    },
    '+Fut+Ind': {
        '+1S+Act': ['amabo'],
        '+2S+Act': ['amabis'],
        '+3S+Act': ['amabit'],
        '+1P+Act': ['amabimus'],
        '+2P+Act': ['amabitis'],
        '+3P+Act': ['amabunt'],
        '+1S+Pass': ['amabor'],
        '+2S+Pass': ['amaberis', 'amabere'],
        '+3S+Pass': ['amabitur'],
        '+1P+Pass': ['amabimur'],
        '+2P+Pass': ['amabimini'],
        '+3P+Pass': ['amabuntur'],
    },
    '+Perf+Ind': {
        '+1S+Act': ['amavi'],
        '+2S+Act': ['amavisti', 'amasti'],
        '+3S+Act': ['amavit'],
        '+1P+Act': ['amavimus'],
        '+2P+Act': ['amavistis', 'amastis'],
        '+3P+Act': ['amaverunt', 'amavere', 'amarunt'],
    },
    '+Perf+Subj': {
        '+1S+Act': ['amaverim',   'amarim'],
        '+2S+Act': ['amaveris',   'amaris'],
        '+3S+Act': ['amaverit',   'amarit'],
        '+1P+Act': ['amaverimus', 'amarimus'],
        '+2P+Act': ['amaveritis', 'amaritis'],
        '+3P+Act': ['amaverint',  'amarint'],
    },
    '+Pqp+Ind': {
        '+1S+Act': ['amaveram',  'amaram'],
        '+2S+Act': ['amaveras',  'amaras'],
        '+3S+Act': ['amaverat',  'amarat'],
        '+1P+Act': ['amaveramus','amaramus'],
        '+2P+Act': ['amaveratis','amaratis'],
        '+3P+Act': ['amaverant', 'amarant'],
    },
    '+Pqp+Subj': {
        '+1S+Act': ['amavissem',   'amassem'],
        '+2S+Act': ['amavisses',   'amasses'],
        '+3S+Act': ['amavisset',   'amasset'],
        '+1P+Act': ['amavissemus', 'amassemus'],
        '+2P+Act': ['amavissetis', 'amassetis'],
        '+3P+Act': ['amavissent',  'amassent'],
    },
    '+FutII+Ind': {
        '+1S+Act': ['amavero',   'amaro'],
        '+2S+Act': ['amaveris',  'amaris'],
        '+3S+Act': ['amaverit',  'amarit'],
        '+1P+Act': ['amaverimus','amarimus'],
        '+2P+Act': ['amaveritis','amaritis'],
        '+3P+Act': ['amaverint', 'amarint'],
    },
    '+Pres+Impv': {
        '+2S+Act' : ['ama'],
        '+2P+Act' : ['amate'],
        '+2S+Pass': ['amare'],
        '+2P+Pass': ['amamini'],
    },
    '+Fut+Impv': {
        '+2S+Act': ['amato'],
        '+3S+Act': ['amato'],
        '+2P+Act': ['amatote'],
        '+3P+Act': ['amanto'],
    },
    '+Inf': {
        '+Pres+Act': ['amare'],
        '+Pres+Pass': ['amari'],
        '+Perf+Act': ['amavisse', 'amasse'],
    }
})
