#!/usr/bin/python

from morph import *
from TAP.Simple import *

plan(239)

test_hash('audio+Verb', {
    '+Pres+Ind': {
        '+1S+Act': ['audio'],
        '+2S+Act': ['audis'],
        '+3S+Act': ['audit'],
        '+1P+Act': ['audimus'],
        '+2P+Act': ['auditis'],
        '+3P+Act': ['audiunt'],
        '+1S+Pass': ['audior'],
        '+2S+Pass': ['audiris', 'audire'],
        '+3S+Pass': ['auditur'],
        '+1P+Pass': ['audimur'],
        '+2P+Pass': ['audimini'],
        '+3P+Pass': ['audiuntur'],
    },
    '+Pres+Subj': {
        '+1S+Act': ['audiam'],
        '+2S+Act': ['audias'],
        '+3S+Act': ['audiat'],
        '+1P+Act': ['audiamus'],
        '+2P+Act': ['audiatis'],
        '+3P+Act': ['audiant'],
        '+1S+Pass': ['audiar'],
        '+2S+Pass': ['audiaris', 'audiare'],
        '+3S+Pass': ['audiatur'],
        '+1P+Pass': ['audiamur'],
        '+2P+Pass': ['audiamini'],
        '+3P+Pass': ['audiantur'],
    },
    '+Impf+Ind': {
        '+1S+Act': ['audiebam'],
        '+2S+Act': ['audiebas'],
        '+3S+Act': ['audiebat'],
        '+1P+Act': ['audiebamus'],
        '+2P+Act': ['audiebatis'],
        '+3P+Act': ['audiebant'],
        '+1S+Pass': ['audiebar'],
        '+2S+Pass': ['audiebaris', 'audiebare'],
        '+3S+Pass': ['audiebatur'],
        '+1P+Pass': ['audiebamur'],
        '+2P+Pass': ['audiebamini'],
        '+3P+Pass': ['audiebantur'],
    },
    '+Impf+Subj': {
        '+1S+Act': ['audirem'],
        '+2S+Act': ['audires'],
        '+3S+Act': ['audiret'],
        '+1P+Act': ['audiremus'],
        '+2P+Act': ['audiretis'],
        '+3P+Act': ['audirent'],
        '+1S+Pass': ['audirer'],
        '+2S+Pass': ['audireris', 'audirere'],
        '+3S+Pass': ['audiretur'],
        '+1P+Pass': ['audiremur'],
        '+2P+Pass': ['audiremini'],
        '+3P+Pass': ['audirentur'],
    },
    '+Fut+Ind': {
        '+1S+Act': ['audiam'],
        '+2S+Act': ['audies'],
        '+3S+Act': ['audiet'],
        '+1P+Act': ['audiemus'],
        '+2P+Act': ['audietis'],
        '+3P+Act': ['audient'],
        '+1S+Pass': ['audiar'],
        '+2S+Pass': ['audieris', 'audiere'],
        '+3S+Pass': ['audietur'],
        '+1P+Pass': ['audiemur'],
        '+2P+Pass': ['audiemini'],
        '+3P+Pass': ['audientur'],
    },
    '+Perf+Ind': {
        '+1S+Act': ['audivi', 'audii'],
        '+2S+Act': ['audivisti', 'audisti'],
        '+3S+Act': ['audivit', 'audiit'],
        '+1P+Act': ['audivimus', 'audiimus'],
        '+2P+Act': ['audivistis', 'audistis'],
        '+3P+Act': ['audiverunt', 'audivere', 'audierunt'],
    },
    '+Perf+Subj': {
        '+1S+Act': ['audiverim',   'audierim'],
        '+2S+Act': ['audiveris',   'audieris'],
        '+3S+Act': ['audiverit',   'audierit'],
        '+1P+Act': ['audiverimus', 'audierimus'],
        '+2P+Act': ['audiveritis', 'audieritis'],
        '+3P+Act': ['audiverint',  'audierint'],
    },
    '+Pqp+Ind': {
        '+1S+Act': ['audiveram',   'audieram'],
        '+2S+Act': ['audiveras',   'audieras'],
        '+3S+Act': ['audiverat',   'audierat'],
        '+1P+Act': ['audiveramus', 'audieramus'],
        '+2P+Act': ['audiveratis', 'audieratis'],
        '+3P+Act': ['audiverant',  'audierant'],
    },
    '+Pqp+Subj': {
        '+1S+Act': ['audivissem',   'audissem'],
        '+2S+Act': ['audivisses',   'audisses'],
        '+3S+Act': ['audivisset',   'audisset'],
        '+1P+Act': ['audivissemus', 'audissemus'],
        '+2P+Act': ['audivissetis', 'audissetis'],
        '+3P+Act': ['audivissent',  'audissent'],
    },
    '+FutII+Ind': {
        '+1S+Act': ['audivero',    'audiero'],
        '+2S+Act': ['audiveris',   'audieris'],
        '+3S+Act': ['audiverit',   'audierit'],
        '+1P+Act': ['audiverimus', 'audierimus'],
        '+2P+Act': ['audiveritis', 'audieritis'],
        '+3P+Act': ['audiverint',  'audierint'],
    },
    '+Pres+Impv': {
        '+2S+Act' : ['audi'],
        '+2P+Act' : ['audite'],
        '+2S+Pass': ['audire'],
        '+2P+Pass': ['audimini'],
    },
    '+Fut+Impv': {
        '+2S+Act': ['audito'],
        '+3S+Act': ['audito'],
        '+2P+Act': ['auditote'],
        '+3P+Act': ['audiunto'],
    },
    '+Inf': {
        '+Pres+Act': ['audire'],
        '+Pres+Pass': ['audiri'],
        '+Perf+Act': ['audivisse', 'audisse'],
    }
})
