use Morph;
use Test::More;

plan(tests => 543);

test_hash('audio+Verb', {
    '+Pres+Ind' => {
        '+1st+Sg+Act' => ['audio'],
        '+2nd+Sg+Act' => ['audis'],
        '+3rd+Sg+Act' => ['audit'],
        '+1st+Pl+Act' => ['audimus'],
        '+2nd+Pl+Act' => ['auditis'],
        '+3rd+Pl+Act' => ['audiunt'],
        '+1st+Sg+Pass' => ['audior'],
        '+2nd+Sg+Pass' => ['audiris', 'audire'],
        '+3rd+Sg+Pass' => ['auditur'],
        '+1st+Pl+Pass' => ['audimur'],
        '+2nd+Pl+Pass' => ['audimini'],
        '+3rd+Pl+Pass' => ['audiuntur'],
    },
    '+Pres+Subj' => {
        '+1st+Sg+Act' => ['audiam'],
        '+2nd+Sg+Act' => ['audias'],
        '+3rd+Sg+Act' => ['audiat'],
        '+1st+Pl+Act' => ['audiamus'],
        '+2nd+Pl+Act' => ['audiatis'],
        '+3rd+Pl+Act' => ['audiant'],
        '+1st+Sg+Pass' => ['audiar'],
        '+2nd+Sg+Pass' => ['audiaris', 'audiare'],
        '+3rd+Sg+Pass' => ['audiatur'],
        '+1st+Pl+Pass' => ['audiamur'],
        '+2nd+Pl+Pass' => ['audiamini'],
        '+3rd+Pl+Pass' => ['audiantur'],
    },
    '+Impf+Ind' => {
        '+1st+Sg+Act' => ['audiebam'],
        '+2nd+Sg+Act' => ['audiebas'],
        '+3rd+Sg+Act' => ['audiebat'],
        '+1st+Pl+Act' => ['audiebamus'],
        '+2nd+Pl+Act' => ['audiebatis'],
        '+3rd+Pl+Act' => ['audiebant'],
        '+1st+Sg+Pass' => ['audiebar'],
        '+2nd+Sg+Pass' => ['audiebaris', 'audiebare'],
        '+3rd+Sg+Pass' => ['audiebatur'],
        '+1st+Pl+Pass' => ['audiebamur'],
        '+2nd+Pl+Pass' => ['audiebamini'],
        '+3rd+Pl+Pass' => ['audiebantur'],
    },
    '+Impf+Subj' => {
        '+1st+Sg+Act' => ['audirem'],
        '+2nd+Sg+Act' => ['audires'],
        '+3rd+Sg+Act' => ['audiret'],
        '+1st+Pl+Act' => ['audiremus'],
        '+2nd+Pl+Act' => ['audiretis'],
        '+3rd+Pl+Act' => ['audirent'],
        '+1st+Sg+Pass' => ['audirer'],
        '+2nd+Sg+Pass' => ['audireris', 'audirere'],
        '+3rd+Sg+Pass' => ['audiretur'],
        '+1st+Pl+Pass' => ['audiremur'],
        '+2nd+Pl+Pass' => ['audiremini'],
        '+3rd+Pl+Pass' => ['audirentur'],
    },
    '+Fut+Ind' => {
        '+1st+Sg+Act' => ['audiam'],
        '+2nd+Sg+Act' => ['audies'],
        '+3rd+Sg+Act' => ['audiet'],
        '+1st+Pl+Act' => ['audiemus'],
        '+2nd+Pl+Act' => ['audietis'],
        '+3rd+Pl+Act' => ['audient'],
        '+1st+Sg+Pass' => ['audiar'],
        '+2nd+Sg+Pass' => ['audieris', 'audiere'],
        '+3rd+Sg+Pass' => ['audietur'],
        '+1st+Pl+Pass' => ['audiemur'],
        '+2nd+Pl+Pass' => ['audiemini'],
        '+3rd+Pl+Pass' => ['audientur'],
    },
    '+Perf+Ind' => {
        '+1st+Sg+Act' => ['audivi', 'audii'],
        '+2nd+Sg+Act' => ['audivisti', 'audisti'],
        '+3rd+Sg+Act' => ['audivit', 'audiit'],
        '+1st+Pl+Act' => ['audivimus', 'audiimus'],
        '+2nd+Pl+Act' => ['audivistis', 'audistis'],
        '+3rd+Pl+Act' => ['audiverunt', 'audivere', 'audierunt', 'audiere'],
    },
    '+Perf+Subj' => {
        '+1st+Sg+Act' => ['audiverim',   'audierim'],
        '+2nd+Sg+Act' => ['audiveris',   'audieris'],
        '+3rd+Sg+Act' => ['audiverit',   'audierit'],
        '+1st+Pl+Act' => ['audiverimus', 'audierimus'],
        '+2nd+Pl+Act' => ['audiveritis', 'audieritis'],
        '+3rd+Pl+Act' => ['audiverint',  'audierint'],
    },
    '+Pqp+Ind' => {
        '+1st+Sg+Act' => ['audiveram',   'audieram'],
        '+2nd+Sg+Act' => ['audiveras',   'audieras'],
        '+3rd+Sg+Act' => ['audiverat',   'audierat'],
        '+1st+Pl+Act' => ['audiveramus', 'audieramus'],
        '+2nd+Pl+Act' => ['audiveratis', 'audieratis'],
        '+3rd+Pl+Act' => ['audiverant',  'audierant'],
    },
    '+Pqp+Subj' => {
        '+1st+Sg+Act' => ['audivissem',   'audissem'],
        '+2nd+Sg+Act' => ['audivisses',   'audisses'],
        '+3rd+Sg+Act' => ['audivisset',   'audisset'],
        '+1st+Pl+Act' => ['audivissemus', 'audissemus'],
        '+2nd+Pl+Act' => ['audivissetis', 'audissetis'],
        '+3rd+Pl+Act' => ['audivissent',  'audissent'],
    },
    '+FutII+Ind' => {
        '+1st+Sg+Act' => ['audivero',    'audiero'],
        '+2nd+Sg+Act' => ['audiveris',   'audieris'],
        '+3rd+Sg+Act' => ['audiverit',   'audierit'],
        '+1st+Pl+Act' => ['audiverimus', 'audierimus'],
        '+2nd+Pl+Act' => ['audiveritis', 'audieritis'],
        '+3rd+Pl+Act' => ['audiverint',  'audierint'],
    },
    '+Pres+Impv' => {
        '+2nd+Sg+Act'  => ['audi'],
        '+2nd+Pl+Act'  => ['audite'],
        '+2nd+Sg+Pass' => ['audire'],
        '+2nd+Pl+Pass' => ['audimini'],
    },
    '+Fut+Impv' => {
        '+2nd+Sg+Act' => ['audito'],
        '+3rd+Sg+Act' => ['audito'],
        '+2nd+Pl+Act' => ['auditote'],
        '+3rd+Pl+Act' => ['audiunto'],
    },
    '+Inf' => {
        '+Pres+Act' => ['audire'],
        '+Pres+Pass' => ['audiri'],
        '+Perf+Act' => ['audivisse', 'audisse'],
    },
    '+Part' => {
        '+Pres' => {
            '+Masc' => {
                '+Nom+Sg' => ['audiens'],
                '+Voc+Sg' => ['audiens'],
                '+Acc+Sg' => ['audientem'],
                '+Gen+Sg' => ['audientis'],
                '+Dat+Sg' => ['audienti'],
                '+Abl+Sg' => ['audienti', 'audiente'],

                '+Nom+Pl' => ['audientes'],
                '+Voc+Pl' => ['audientes'],
                '+Acc+Pl' => ['audientes'],
                '+Gen+Pl' => ['audientium'],
                '+Dat+Pl' => ['audientibus'],
                '+Abl+Pl' => ['audientibus'],
            },
            '+Fem' => {
                '+Nom+Sg' => ['audiens'],
                '+Voc+Sg' => ['audiens'],
                '+Acc+Sg' => ['audientem'],
                '+Gen+Sg' => ['audientis'],
                '+Dat+Sg' => ['audienti'],
                '+Abl+Sg' => ['audienti', 'audiente'],

                '+Nom+Pl' => ['audientes'],
                '+Voc+Pl' => ['audientes'],
                '+Acc+Pl' => ['audientes'],
                '+Gen+Pl' => ['audientium'],
                '+Dat+Pl' => ['audientibus'],
                '+Abl+Pl' => ['audientibus'],
            },
            '+Neut' => {
                '+Nom+Sg' => ['audiens'],
                '+Voc+Sg' => ['audiens'],
                '+Acc+Sg' => ['audiens'],
                '+Gen+Sg' => ['audientis'],
                '+Dat+Sg' => ['audienti'],
                '+Abl+Sg' => ['audienti', 'audiente'],

                '+Nom+Pl' => ['audientia'],
                '+Voc+Pl' => ['audientia'],
                '+Acc+Pl' => ['audientia'],
                '+Gen+Pl' => ['audientium'],
                '+Dat+Pl' => ['audientibus'],
                '+Abl+Pl' => ['audientibus'],
            },
        },
        '+Perf' => {
            '+Masc' => {
                '+Nom+Sg' => ['auditus'],
                '+Voc+Sg' => ['audite'],
                '+Acc+Sg' => ['auditum'],
                '+Gen+Sg' => ['auditi'],
                '+Dat+Sg' => ['audito'],
                '+Abl+Sg' => ['audito'],

                '+Nom+Pl' => ['auditi'],
                '+Voc+Pl' => ['auditi'],
                '+Acc+Pl' => ['auditos'],
                '+Gen+Pl' => ['auditorum'],
                '+Dat+Pl' => ['auditis'],
                '+Abl+Pl' => ['auditis'],
            },
            '+Fem' => {
                '+Nom+Sg' => ['audita'],
                '+Voc+Sg' => ['audita'],
                '+Acc+Sg' => ['auditam'],
                '+Gen+Sg' => ['auditae'],
                '+Dat+Sg' => ['auditae'],
                '+Abl+Sg' => ['audita'],

                '+Nom+Pl' => ['auditae'],
                '+Voc+Pl' => ['auditae'],
                '+Acc+Pl' => ['auditas'],
                '+Gen+Pl' => ['auditarum'],
                '+Dat+Pl' => ['auditis'],
                '+Abl+Pl' => ['auditis'],
            },
            '+Neut' => {
                '+Nom+Sg' => ['auditum'],
                '+Voc+Sg' => ['auditum'],
                '+Acc+Sg' => ['auditum'],
                '+Gen+Sg' => ['auditi'],
                '+Dat+Sg' => ['audito'],
                '+Abl+Sg' => ['audito'],

                '+Nom+Pl' => ['audita'],
                '+Voc+Pl' => ['audita'],
                '+Acc+Pl' => ['audita'],
                '+Gen+Pl' => ['auditorum'],
                '+Dat+Pl' => ['auditis'],
                '+Abl+Pl' => ['auditis'],
            },
        },
        '+Fut' => {
            '+Masc' => {
                '+Nom+Sg' => ['auditurus'],
                '+Voc+Sg' => ['auditure'],
                '+Acc+Sg' => ['auditurum'],
                '+Gen+Sg' => ['audituri'],
                '+Dat+Sg' => ['audituro'],
                '+Abl+Sg' => ['audituro'],

                '+Nom+Pl' => ['audituri'],
                '+Voc+Pl' => ['audituri'],
                '+Acc+Pl' => ['audituros'],
                '+Gen+Pl' => ['auditurorum'],
                '+Dat+Pl' => ['audituris'],
                '+Abl+Pl' => ['audituris'],
            },
            '+Fem' => {
                '+Nom+Sg' => ['auditura'],
                '+Voc+Sg' => ['auditura'],
                '+Acc+Sg' => ['audituram'],
                '+Gen+Sg' => ['auditurae'],
                '+Dat+Sg' => ['auditurae'],
                '+Abl+Sg' => ['auditura'],

                '+Nom+Pl' => ['auditurae'],
                '+Voc+Pl' => ['auditurae'],
                '+Acc+Pl' => ['audituras'],
                '+Gen+Pl' => ['auditurarum'],
                '+Dat+Pl' => ['audituris'],
                '+Abl+Pl' => ['audituris'],
            },
            '+Neut' => {
                '+Nom+Sg' => ['auditurum'],
                '+Voc+Sg' => ['auditurum'],
                '+Acc+Sg' => ['auditurum'],
                '+Gen+Sg' => ['audituri'],
                '+Dat+Sg' => ['audituro'],
                '+Abl+Sg' => ['audituro'],

                '+Nom+Pl' => ['auditura'],
                '+Voc+Pl' => ['auditura'],
                '+Acc+Pl' => ['auditura'],
                '+Gen+Pl' => ['auditurorum'],
                '+Dat+Pl' => ['audituris'],
                '+Abl+Pl' => ['audituris'],
            },
        },
    },
    '+Ger' => {
        '+Acc' => ['audiendum'],
        '+Gen' => ['audiendi'],
        '+Dat' => ['audiendo'],
        '+Abl' => ['audiendo'],
    },
    '+Gerv' => {
        '+Masc' => {
            '+Nom+Sg' => ['audiendus'],
            '+Voc+Sg' => ['audiende'],
            '+Acc+Sg' => ['audiendum'],
            '+Gen+Sg' => ['audiendi'],
            '+Dat+Sg' => ['audiendo'],
            '+Abl+Sg' => ['audiendo'],

            '+Nom+Pl' => ['audiendi'],
            '+Voc+Pl' => ['audiendi'],
            '+Acc+Pl' => ['audiendos'],
            '+Gen+Pl' => ['audiendorum'],
            '+Dat+Pl' => ['audiendis'],
            '+Abl+Pl' => ['audiendis'],
        },
        '+Fem' => {
            '+Nom+Sg' => ['audienda'],
            '+Voc+Sg' => ['audienda'],
            '+Acc+Sg' => ['audiendam'],
            '+Gen+Sg' => ['audiendae'],
            '+Dat+Sg' => ['audiendae'],
            '+Abl+Sg' => ['audienda'],

            '+Nom+Pl' => ['audiendae'],
            '+Voc+Pl' => ['audiendae'],
            '+Acc+Pl' => ['audiendas'],
            '+Gen+Pl' => ['audiendarum'],
            '+Dat+Pl' => ['audiendis'],
            '+Abl+Pl' => ['audiendis'],
        },
        '+Neut' => {
            '+Nom+Sg' => ['audiendum'],
            '+Voc+Sg' => ['audiendum'],
            '+Acc+Sg' => ['audiendum'],
            '+Gen+Sg' => ['audiendi'],
            '+Dat+Sg' => ['audiendo'],
            '+Abl+Sg' => ['audiendo'],

            '+Nom+Pl' => ['audienda'],
            '+Voc+Pl' => ['audienda'],
            '+Acc+Pl' => ['audienda'],
            '+Gen+Pl' => ['audiendorum'],
            '+Dat+Pl' => ['audiendis'],
            '+Abl+Pl' => ['audiendis'],
        },
    },
    '+SupI' => ['auditum'],
    '+SupII' => ['auditu'],
});
