#!/usr/bin/env python

from morph import *
from TAP.Simple import *

plan(511)

test_hash('capio+Verb', {
    '+Pres+Ind': {
        '+1st+Sg+Act': ['capio'],
        '+2nd+Sg+Act': ['capis'],
        '+3rd+Sg+Act': ['capit'],
        '+1st+Pl+Act': ['capimus'],
        '+2nd+Pl+Act': ['capitis'],
        '+3rd+Pl+Act': ['capiunt'],
        '+1st+Sg+Pass': ['capior'],
        '+2nd+Sg+Pass': ['caperis', 'capere'],
        '+3rd+Sg+Pass': ['capitur'],
        '+1st+Pl+Pass': ['capimur'],
        '+2nd+Pl+Pass': ['capimini'],
        '+3rd+Pl+Pass': ['capiuntur'],
    },
    '+Pres+Subj': {
        '+1st+Sg+Act': ['capiam'],
        '+2nd+Sg+Act': ['capias'],
        '+3rd+Sg+Act': ['capiat'],
        '+1st+Pl+Act': ['capiamus'],
        '+2nd+Pl+Act': ['capiatis'],
        '+3rd+Pl+Act': ['capiant'],
        '+1st+Sg+Pass': ['capiar'],
        '+2nd+Sg+Pass': ['capiaris', 'capiare'],
        '+3rd+Sg+Pass': ['capiatur'],
        '+1st+Pl+Pass': ['capiamur'],
        '+2nd+Pl+Pass': ['capiamini'],
        '+3rd+Pl+Pass': ['capiantur'],
    },
    '+Impf+Ind': {
        '+1st+Sg+Act': ['capiebam'],
        '+2nd+Sg+Act': ['capiebas'],
        '+3rd+Sg+Act': ['capiebat'],
        '+1st+Pl+Act': ['capiebamus'],
        '+2nd+Pl+Act': ['capiebatis'],
        '+3rd+Pl+Act': ['capiebant'],
        '+1st+Sg+Pass': ['capiebar'],
        '+2nd+Sg+Pass': ['capiebaris', 'capiebare'],
        '+3rd+Sg+Pass': ['capiebatur'],
        '+1st+Pl+Pass': ['capiebamur'],
        '+2nd+Pl+Pass': ['capiebamini'],
        '+3rd+Pl+Pass': ['capiebantur'],
    },
    '+Impf+Subj': {
        '+1st+Sg+Act': ['caperem'],
        '+2nd+Sg+Act': ['caperes'],
        '+3rd+Sg+Act': ['caperet'],
        '+1st+Pl+Act': ['caperemus'],
        '+2nd+Pl+Act': ['caperetis'],
        '+3rd+Pl+Act': ['caperent'],
        '+1st+Sg+Pass': ['caperer'],
        '+2nd+Sg+Pass': ['capereris', 'caperere'],
        '+3rd+Sg+Pass': ['caperetur'],
        '+1st+Pl+Pass': ['caperemur'],
        '+2nd+Pl+Pass': ['caperemini'],
        '+3rd+Pl+Pass': ['caperentur'],
    },
    '+Fut+Ind': {
        '+1st+Sg+Act': ['capiam'],
        '+2nd+Sg+Act': ['capies'],
        '+3rd+Sg+Act': ['capiet'],
        '+1st+Pl+Act': ['capiemus'],
        '+2nd+Pl+Act': ['capietis'],
        '+3rd+Pl+Act': ['capient'],
        '+1st+Sg+Pass': ['capiar'],
        '+2nd+Sg+Pass': ['capieris', 'capiere'],
        '+3rd+Sg+Pass': ['capietur'],
        '+1st+Pl+Pass': ['capiemur'],
        '+2nd+Pl+Pass': ['capiemini'],
        '+3rd+Pl+Pass': ['capientur'],
    },
    '+Perf+Ind': {
        '+1st+Sg+Act': ['cepi'],
        '+2nd+Sg+Act': ['cepisti'],
        '+3rd+Sg+Act': ['cepit'],
        '+1st+Pl+Act': ['cepimus'],
        '+2nd+Pl+Act': ['cepistis'],
        '+3rd+Pl+Act': ['ceperunt', 'cepere'],
    },
    '+Perf+Subj': {
        '+1st+Sg+Act': ['ceperim'],
        '+2nd+Sg+Act': ['ceperis'],
        '+3rd+Sg+Act': ['ceperit'],
        '+1st+Pl+Act': ['ceperimus'],
        '+2nd+Pl+Act': ['ceperitis'],
        '+3rd+Pl+Act': ['ceperint'],
    },
    '+Pqp+Ind': {
        '+1st+Sg+Act': ['ceperam'],
        '+2nd+Sg+Act': ['ceperas'],
        '+3rd+Sg+Act': ['ceperat'],
        '+1st+Pl+Act': ['ceperamus'],
        '+2nd+Pl+Act': ['ceperatis'],
        '+3rd+Pl+Act': ['ceperant'],
    },
    '+Pqp+Subj': {
        '+1st+Sg+Act': ['cepissem'],
        '+2nd+Sg+Act': ['cepisses'],
        '+3rd+Sg+Act': ['cepisset'],
        '+1st+Pl+Act': ['cepissemus'],
        '+2nd+Pl+Act': ['cepissetis'],
        '+3rd+Pl+Act': ['cepissent'],
    },
    '+FutII+Ind': {
        '+1st+Sg+Act': ['cepero'],
        '+2nd+Sg+Act': ['ceperis'],
        '+3rd+Sg+Act': ['ceperit'],
        '+1st+Pl+Act': ['ceperimus'],
        '+2nd+Pl+Act': ['ceperitis'],
        '+3rd+Pl+Act': ['ceperint'],
    },
    '+Pres+Impv': {
        '+2nd+Sg+Act' : ['cape'],
        '+2nd+Pl+Act' : ['capite'],
        '+2nd+Sg+Pass': ['capere'],
        '+2nd+Pl+Pass': ['capimini'],
    },
    '+Fut+Impv': {
        '+2nd+Sg+Act': ['capito'],
        '+3rd+Sg+Act': ['capito'],
        '+2nd+Pl+Act': ['capitote'],
        '+3rd+Pl+Act': ['capiunto'],
    },
    '+Inf': {
        '+Pres+Act': ['capere'],
        '+Pres+Pass': ['capi'],
        '+Perf+Act': ['cepisse'],
    },
    '+Part': {
        '+Pres': {
            '+Masc': {
                '+Nom+Sg': ['capiens'],
                '+Voc+Sg': ['capiens'],
                '+Acc+Sg': ['capientem'],
                '+Gen+Sg': ['capientis'],
                '+Dat+Sg': ['capienti'],
                '+Abl+Sg': ['capienti', 'capiente'],

                '+Nom+Pl': ['capientes'],
                '+Voc+Pl': ['capientes'],
                '+Acc+Pl': ['capientes'],
                '+Gen+Pl': ['capientium'],
                '+Dat+Pl': ['capientibus'],
                '+Abl+Pl': ['capientibus'],
            },
            '+Fem': {
                '+Nom+Sg': ['capiens'],
                '+Voc+Sg': ['capiens'],
                '+Acc+Sg': ['capientem'],
                '+Gen+Sg': ['capientis'],
                '+Dat+Sg': ['capienti'],
                '+Abl+Sg': ['capienti', 'capiente'],

                '+Nom+Pl': ['capientes'],
                '+Voc+Pl': ['capientes'],
                '+Acc+Pl': ['capientes'],
                '+Gen+Pl': ['capientium'],
                '+Dat+Pl': ['capientibus'],
                '+Abl+Pl': ['capientibus'],
            },
            '+Neut': {
                '+Nom+Sg': ['capiens'],
                '+Voc+Sg': ['capiens'],
                '+Acc+Sg': ['capiens'],
                '+Gen+Sg': ['capientis'],
                '+Dat+Sg': ['capienti'],
                '+Abl+Sg': ['capienti', 'capiente'],

                '+Nom+Pl': ['capientia'],
                '+Voc+Pl': ['capientia'],
                '+Acc+Pl': ['capientia'],
                '+Gen+Pl': ['capientium'],
                '+Dat+Pl': ['capientibus'],
                '+Abl+Pl': ['capientibus'],
            },
        },
        '+Perf': {
            '+Masc': {
                '+Nom+Sg': ['captus'],
                '+Voc+Sg': ['capte'],
                '+Acc+Sg': ['captum'],
                '+Gen+Sg': ['capti'],
                '+Dat+Sg': ['capto'],
                '+Abl+Sg': ['capto'],

                '+Nom+Pl': ['capti'],
                '+Voc+Pl': ['capti'],
                '+Acc+Pl': ['captos'],
                '+Gen+Pl': ['captorum'],
                '+Dat+Pl': ['captis'],
                '+Abl+Pl': ['captis'],
            },
            '+Fem': {
                '+Nom+Sg': ['capta'],
                '+Voc+Sg': ['capta'],
                '+Acc+Sg': ['captam'],
                '+Gen+Sg': ['captae'],
                '+Dat+Sg': ['captae'],
                '+Abl+Sg': ['capta'],

                '+Nom+Pl': ['captae'],
                '+Voc+Pl': ['captae'],
                '+Acc+Pl': ['captas'],
                '+Gen+Pl': ['captarum'],
                '+Dat+Pl': ['captis'],
                '+Abl+Pl': ['captis'],
            },
            '+Neut': {
                '+Nom+Sg': ['captum'],
                '+Voc+Sg': ['captum'],
                '+Acc+Sg': ['captum'],
                '+Gen+Sg': ['capti'],
                '+Dat+Sg': ['capto'],
                '+Abl+Sg': ['capto'],

                '+Nom+Pl': ['capta'],
                '+Voc+Pl': ['capta'],
                '+Acc+Pl': ['capta'],
                '+Gen+Pl': ['captorum'],
                '+Dat+Pl': ['captis'],
                '+Abl+Pl': ['captis'],
            },
        },
        '+Fut': {
            '+Masc': {
                '+Nom+Sg': ['capturus'],
                '+Voc+Sg': ['capture'],
                '+Acc+Sg': ['capturum'],
                '+Gen+Sg': ['capturi'],
                '+Dat+Sg': ['capturo'],
                '+Abl+Sg': ['capturo'],

                '+Nom+Pl': ['capturi'],
                '+Voc+Pl': ['capturi'],
                '+Acc+Pl': ['capturos'],
                '+Gen+Pl': ['capturorum'],
                '+Dat+Pl': ['capturis'],
                '+Abl+Pl': ['capturis'],
            },
            '+Fem': {
                '+Nom+Sg': ['captura'],
                '+Voc+Sg': ['captura'],
                '+Acc+Sg': ['capturam'],
                '+Gen+Sg': ['capturae'],
                '+Dat+Sg': ['capturae'],
                '+Abl+Sg': ['captura'],

                '+Nom+Pl': ['capturae'],
                '+Voc+Pl': ['capturae'],
                '+Acc+Pl': ['capturas'],
                '+Gen+Pl': ['capturarum'],
                '+Dat+Pl': ['capturis'],
                '+Abl+Pl': ['capturis'],
            },
            '+Neut': {
                '+Nom+Sg': ['capturum'],
                '+Voc+Sg': ['capturum'],
                '+Acc+Sg': ['capturum'],
                '+Gen+Sg': ['capturi'],
                '+Dat+Sg': ['capturo'],
                '+Abl+Sg': ['capturo'],

                '+Nom+Pl': ['captura'],
                '+Voc+Pl': ['captura'],
                '+Acc+Pl': ['captura'],
                '+Gen+Pl': ['capturorum'],
                '+Dat+Pl': ['capturis'],
                '+Abl+Pl': ['capturis'],
            },
        },
    },
    '+Ger': {
        '+Acc': ['capiendum'],
        '+Gen': ['capiendi'],
        '+Dat': ['capiendo'],
        '+Abl': ['capiendo'],
    },
    '+Gerv': {
        '+Masc': {
            '+Nom+Sg': ['capiendus'],
            '+Voc+Sg': ['capiende'],
            '+Acc+Sg': ['capiendum'],
            '+Gen+Sg': ['capiendi'],
            '+Dat+Sg': ['capiendo'],
            '+Abl+Sg': ['capiendo'],

            '+Nom+Pl': ['capiendi'],
            '+Voc+Pl': ['capiendi'],
            '+Acc+Pl': ['capiendos'],
            '+Gen+Pl': ['capiendorum'],
            '+Dat+Pl': ['capiendis'],
            '+Abl+Pl': ['capiendis'],
        },
        '+Fem': {
            '+Nom+Sg': ['capienda'],
            '+Voc+Sg': ['capienda'],
            '+Acc+Sg': ['capiendam'],
            '+Gen+Sg': ['capiendae'],
            '+Dat+Sg': ['capiendae'],
            '+Abl+Sg': ['capienda'],

            '+Nom+Pl': ['capiendae'],
            '+Voc+Pl': ['capiendae'],
            '+Acc+Pl': ['capiendas'],
            '+Gen+Pl': ['capiendarum'],
            '+Dat+Pl': ['capiendis'],
            '+Abl+Pl': ['capiendis'],
        },
        '+Neut': {
            '+Nom+Sg': ['capiendum'],
            '+Voc+Sg': ['capiendum'],
            '+Acc+Sg': ['capiendum'],
            '+Gen+Sg': ['capiendi'],
            '+Dat+Sg': ['capiendo'],
            '+Abl+Sg': ['capiendo'],

            '+Nom+Pl': ['capienda'],
            '+Voc+Pl': ['capienda'],
            '+Acc+Pl': ['capienda'],
            '+Gen+Pl': ['capiendorum'],
            '+Dat+Pl': ['capiendis'],
            '+Abl+Pl': ['capiendis'],
        },
    },
    '+SupI': ['captum'],
    '+SupII': ['captu'],
})
diag("%d" % Morph.formcount)
