use Morph;
use Test::More;

plan(tests => 539);

test_hash('amo+Verb', {
    '+Pres+Ind' => {
        '+1st+Sg+Act' => ['amo'],
        '+2nd+Sg+Act' => ['amas'],
        '+3rd+Sg+Act' => ['amat'],
        '+1st+Pl+Act' => ['amamus'],
        '+2nd+Pl+Act' => ['amatis'],
        '+3rd+Pl+Act' => ['amant'],
        '+1st+Sg+Pass' => ['amor'],
        '+2nd+Sg+Pass' => ['amaris', 'amare'],
        '+3rd+Sg+Pass' => ['amatur'],
        '+1st+Pl+Pass' => ['amamur'],
        '+2nd+Pl+Pass' => ['amamini'],
        '+3rd+Pl+Pass' => ['amantur'],
    },
    '+Pres+Subj' => {
        '+1st+Sg+Act' => ['amem'],
        '+2nd+Sg+Act' => ['ames'],
        '+3rd+Sg+Act' => ['amet'],
        '+1st+Pl+Act' => ['amemus'],
        '+2nd+Pl+Act' => ['ametis'],
        '+3rd+Pl+Act' => ['ament'],
        '+1st+Sg+Pass' => ['amer'],
        '+2nd+Sg+Pass' => ['ameris', 'amere'],
        '+3rd+Sg+Pass' => ['ametur'],
        '+1st+Pl+Pass' => ['amemur'],
        '+2nd+Pl+Pass' => ['amemini'],
        '+3rd+Pl+Pass' => ['amentur'],
    },
    '+Impf+Ind' => {
        '+1st+Sg+Act' => ['amabam'],
        '+2nd+Sg+Act' => ['amabas'],
        '+3rd+Sg+Act' => ['amabat'],
        '+1st+Pl+Act' => ['amabamus'],
        '+2nd+Pl+Act' => ['amabatis'],
        '+3rd+Pl+Act' => ['amabant'],
        '+1st+Sg+Pass' => ['amabar'],
        '+2nd+Sg+Pass' => ['amabaris', 'amabare'],
        '+3rd+Sg+Pass' => ['amabatur'],
        '+1st+Pl+Pass' => ['amabamur'],
        '+2nd+Pl+Pass' => ['amabamini'],
        '+3rd+Pl+Pass' => ['amabantur'],
    },
    '+Impf+Subj' => {
        '+1st+Sg+Act' => ['amarem'],
        '+2nd+Sg+Act' => ['amares'],
        '+3rd+Sg+Act' => ['amaret'],
        '+1st+Pl+Act' => ['amaremus'],
        '+2nd+Pl+Act' => ['amaretis'],
        '+3rd+Pl+Act' => ['amarent'],
        '+1st+Sg+Pass' => ['amarer'],
        '+2nd+Sg+Pass' => ['amareris', 'amarere'],
        '+3rd+Sg+Pass' => ['amaretur'],
        '+1st+Pl+Pass' => ['amaremur'],
        '+2nd+Pl+Pass' => ['amaremini'],
        '+3rd+Pl+Pass' => ['amarentur'],
    },
    '+Fut+Ind' => {
        '+1st+Sg+Act' => ['amabo'],
        '+2nd+Sg+Act' => ['amabis'],
        '+3rd+Sg+Act' => ['amabit'],
        '+1st+Pl+Act' => ['amabimus'],
        '+2nd+Pl+Act' => ['amabitis'],
        '+3rd+Pl+Act' => ['amabunt'],
        '+1st+Sg+Pass' => ['amabor'],
        '+2nd+Sg+Pass' => ['amaberis', 'amabere'],
        '+3rd+Sg+Pass' => ['amabitur'],
        '+1st+Pl+Pass' => ['amabimur'],
        '+2nd+Pl+Pass' => ['amabimini'],
        '+3rd+Pl+Pass' => ['amabuntur'],
    },
    '+Perf+Ind' => {
        '+1st+Sg+Act' => ['amavi'],
        '+2nd+Sg+Act' => ['amavisti', 'amasti'],
        '+3rd+Sg+Act' => ['amavit'],
        '+1st+Pl+Act' => ['amavimus'],
        '+2nd+Pl+Act' => ['amavistis', 'amastis'],
        '+3rd+Pl+Act' => ['amaverunt', 'amavere', 'amarunt'],
    },
    '+Perf+Subj' => {
        '+1st+Sg+Act' => ['amaverim',   'amarim'],
        '+2nd+Sg+Act' => ['amaveris',   'amaris'],
        '+3rd+Sg+Act' => ['amaverit',   'amarit'],
        '+1st+Pl+Act' => ['amaverimus', 'amarimus'],
        '+2nd+Pl+Act' => ['amaveritis', 'amaritis'],
        '+3rd+Pl+Act' => ['amaverint',  'amarint'],
    },
    '+Pqp+Ind' => {
        '+1st+Sg+Act' => ['amaveram',  'amaram'],
        '+2nd+Sg+Act' => ['amaveras',  'amaras'],
        '+3rd+Sg+Act' => ['amaverat',  'amarat'],
        '+1st+Pl+Act' => ['amaveramus','amaramus'],
        '+2nd+Pl+Act' => ['amaveratis','amaratis'],
        '+3rd+Pl+Act' => ['amaverant', 'amarant'],
    },
    '+Pqp+Subj' => {
        '+1st+Sg+Act' => ['amavissem',   'amassem'],
        '+2nd+Sg+Act' => ['amavisses',   'amasses'],
        '+3rd+Sg+Act' => ['amavisset',   'amasset'],
        '+1st+Pl+Act' => ['amavissemus', 'amassemus'],
        '+2nd+Pl+Act' => ['amavissetis', 'amassetis'],
        '+3rd+Pl+Act' => ['amavissent',  'amassent'],
    },
    '+FutII+Ind' => {
        '+1st+Sg+Act' => ['amavero',   'amaro'],
        '+2nd+Sg+Act' => ['amaveris',  'amaris'],
        '+3rd+Sg+Act' => ['amaverit',  'amarit'],
        '+1st+Pl+Act' => ['amaverimus','amarimus'],
        '+2nd+Pl+Act' => ['amaveritis','amaritis'],
        '+3rd+Pl+Act' => ['amaverint', 'amarint'],
    },
    '+Pres+Impv' => {
        '+2nd+Sg+Act'  => ['ama'],
        '+2nd+Pl+Act'  => ['amate'],
        '+2nd+Sg+Pass' => ['amare'],
        '+2nd+Pl+Pass' => ['amamini'],
    },
    '+Fut+Impv' => {
        '+2nd+Sg+Act' => ['amato'],
        '+3rd+Sg+Act' => ['amato'],
        '+2nd+Pl+Act' => ['amatote'],
        '+3rd+Pl+Act' => ['amanto'],
    },
    '+Inf' => {
        '+Pres+Act' => ['amare'],
        '+Pres+Pass' => ['amari'],
        '+Perf+Act' => ['amavisse', 'amasse'],
    },
    '+Part' => {
        '+Pres' => {
            '+Masc' => {
                '+Nom+Sg' => ['amans'],
                '+Voc+Sg' => ['amans'],
                '+Acc+Sg' => ['amantem'],
                '+Gen+Sg' => ['amantis'],
                '+Dat+Sg' => ['amanti'],
                '+Abl+Sg' => ['amanti', 'amante'],

                '+Nom+Pl' => ['amantes'],
                '+Voc+Pl' => ['amantes'],
                '+Acc+Pl' => ['amantes'],
                '+Gen+Pl' => ['amantium'],
                '+Dat+Pl' => ['amantibus'],
                '+Abl+Pl' => ['amantibus'],
            },
            '+Fem' => {
                '+Nom+Sg' => ['amans'],
                '+Voc+Sg' => ['amans'],
                '+Acc+Sg' => ['amantem'],
                '+Gen+Sg' => ['amantis'],
                '+Dat+Sg' => ['amanti'],
                '+Abl+Sg' => ['amanti', 'amante'],

                '+Nom+Pl' => ['amantes'],
                '+Voc+Pl' => ['amantes'],
                '+Acc+Pl' => ['amantes'],
                '+Gen+Pl' => ['amantium'],
                '+Dat+Pl' => ['amantibus'],
                '+Abl+Pl' => ['amantibus'],
            },
            '+Neut' => {
                '+Nom+Sg' => ['amans'],
                '+Voc+Sg' => ['amans'],
                '+Acc+Sg' => ['amans'],
                '+Gen+Sg' => ['amantis'],
                '+Dat+Sg' => ['amanti'],
                '+Abl+Sg' => ['amanti', 'amante'],

                '+Nom+Pl' => ['amantia'],
                '+Voc+Pl' => ['amantia'],
                '+Acc+Pl' => ['amantia'],
                '+Gen+Pl' => ['amantium'],
                '+Dat+Pl' => ['amantibus'],
                '+Abl+Pl' => ['amantibus'],
            },
        },
        '+Perf' => {
            '+Masc' => {
                '+Nom+Sg' => ['amatus'],
                '+Voc+Sg' => ['amate'],
                '+Acc+Sg' => ['amatum'],
                '+Gen+Sg' => ['amati'],
                '+Dat+Sg' => ['amato'],
                '+Abl+Sg' => ['amato'],

                '+Nom+Pl' => ['amati'],
                '+Voc+Pl' => ['amati'],
                '+Acc+Pl' => ['amatos'],
                '+Gen+Pl' => ['amatorum'],
                '+Dat+Pl' => ['amatis'],
                '+Abl+Pl' => ['amatis'],
            },
            '+Fem' => {
                '+Nom+Sg' => ['amata'],
                '+Voc+Sg' => ['amata'],
                '+Acc+Sg' => ['amatam'],
                '+Gen+Sg' => ['amatae'],
                '+Dat+Sg' => ['amatae'],
                '+Abl+Sg' => ['amata'],

                '+Nom+Pl' => ['amatae'],
                '+Voc+Pl' => ['amatae'],
                '+Acc+Pl' => ['amatas'],
                '+Gen+Pl' => ['amatarum'],
                '+Dat+Pl' => ['amatis'],
                '+Abl+Pl' => ['amatis'],
            },
            '+Neut' => {
                '+Nom+Sg' => ['amatum'],
                '+Voc+Sg' => ['amatum'],
                '+Acc+Sg' => ['amatum'],
                '+Gen+Sg' => ['amati'],
                '+Dat+Sg' => ['amato'],
                '+Abl+Sg' => ['amato'],

                '+Nom+Pl' => ['amata'],
                '+Voc+Pl' => ['amata'],
                '+Acc+Pl' => ['amata'],
                '+Gen+Pl' => ['amatorum'],
                '+Dat+Pl' => ['amatis'],
                '+Abl+Pl' => ['amatis'],
            },
        },
        '+Fut' => {
            '+Masc' => {
                '+Nom+Sg' => ['amaturus'],
                '+Voc+Sg' => ['amature'],
                '+Acc+Sg' => ['amaturum'],
                '+Gen+Sg' => ['amaturi'],
                '+Dat+Sg' => ['amaturo'],
                '+Abl+Sg' => ['amaturo'],

                '+Nom+Pl' => ['amaturi'],
                '+Voc+Pl' => ['amaturi'],
                '+Acc+Pl' => ['amaturos'],
                '+Gen+Pl' => ['amaturorum'],
                '+Dat+Pl' => ['amaturis'],
                '+Abl+Pl' => ['amaturis'],
            },
            '+Fem' => {
                '+Nom+Sg' => ['amatura'],
                '+Voc+Sg' => ['amatura'],
                '+Acc+Sg' => ['amaturam'],
                '+Gen+Sg' => ['amaturae'],
                '+Dat+Sg' => ['amaturae'],
                '+Abl+Sg' => ['amatura'],

                '+Nom+Pl' => ['amaturae'],
                '+Voc+Pl' => ['amaturae'],
                '+Acc+Pl' => ['amaturas'],
                '+Gen+Pl' => ['amaturarum'],
                '+Dat+Pl' => ['amaturis'],
                '+Abl+Pl' => ['amaturis'],
            },
            '+Neut' => {
                '+Nom+Sg' => ['amaturum'],
                '+Voc+Sg' => ['amaturum'],
                '+Acc+Sg' => ['amaturum'],
                '+Gen+Sg' => ['amaturi'],
                '+Dat+Sg' => ['amaturo'],
                '+Abl+Sg' => ['amaturo'],

                '+Nom+Pl' => ['amatura'],
                '+Voc+Pl' => ['amatura'],
                '+Acc+Pl' => ['amatura'],
                '+Gen+Pl' => ['amaturorum'],
                '+Dat+Pl' => ['amaturis'],
                '+Abl+Pl' => ['amaturis'],
            },
        },
    },
    '+Ger' => {
        '+Acc' => ['amandum'],
        '+Gen' => ['amandi'],
        '+Dat' => ['amando'],
        '+Abl' => ['amando'],
    },
    '+Gerv' => {
        '+Masc' => {
            '+Nom+Sg' => ['amandus'],
            '+Voc+Sg' => ['amande'],
            '+Acc+Sg' => ['amandum'],
            '+Gen+Sg' => ['amandi'],
            '+Dat+Sg' => ['amando'],
            '+Abl+Sg' => ['amando'],

            '+Nom+Pl' => ['amandi'],
            '+Voc+Pl' => ['amandi'],
            '+Acc+Pl' => ['amandos'],
            '+Gen+Pl' => ['amandorum'],
            '+Dat+Pl' => ['amandis'],
            '+Abl+Pl' => ['amandis'],
        },
        '+Fem' => {
            '+Nom+Sg' => ['amanda'],
            '+Voc+Sg' => ['amanda'],
            '+Acc+Sg' => ['amandam'],
            '+Gen+Sg' => ['amandae'],
            '+Dat+Sg' => ['amandae'],
            '+Abl+Sg' => ['amanda'],

            '+Nom+Pl' => ['amandae'],
            '+Voc+Pl' => ['amandae'],
            '+Acc+Pl' => ['amandas'],
            '+Gen+Pl' => ['amandarum'],
            '+Dat+Pl' => ['amandis'],
            '+Abl+Pl' => ['amandis'],
        },
        '+Neut' => {
            '+Nom+Sg' => ['amandum'],
            '+Voc+Sg' => ['amandum'],
            '+Acc+Sg' => ['amandum'],
            '+Gen+Sg' => ['amandi'],
            '+Dat+Sg' => ['amando'],
            '+Abl+Sg' => ['amando'],

            '+Nom+Pl' => ['amanda'],
            '+Voc+Pl' => ['amanda'],
            '+Acc+Pl' => ['amanda'],
            '+Gen+Pl' => ['amandorum'],
            '+Dat+Pl' => ['amandis'],
            '+Abl+Pl' => ['amandis'],
        },
    },
    '+SupI' => ['amatum'],
    '+SupII' => ['amatu'],
});
