use Morph;
use Test::More;

plan(tests => 374);

test_hash('patior+Verb+Dep', {
    '+Pres+Ind' => {
        '+1st+Sg+Pass' => ['patior'],
        '+2nd+Sg+Pass' => ['pateris', 'patere'],
        '+3rd+Sg+Pass' => ['patitur'],
        '+1st+Pl+Pass' => ['patimur'],
        '+2nd+Pl+Pass' => ['patimini'],
        '+3rd+Pl+Pass' => ['patiuntur'],
    },
    '+Pres+Subj' => {
        '+1st+Sg+Pass' => ['patiar'],
        '+2nd+Sg+Pass' => ['patiaris', 'patiare'],
        '+3rd+Sg+Pass' => ['patiatur'],
        '+1st+Pl+Pass' => ['patiamur'],
        '+2nd+Pl+Pass' => ['patiamini'],
        '+3rd+Pl+Pass' => ['patiantur'],
    },
    '+Impf+Ind' => {
        '+1st+Sg+Pass' => ['patiebar'],
        '+2nd+Sg+Pass' => ['patiebaris', 'patiebare'],
        '+3rd+Sg+Pass' => ['patiebatur'],
        '+1st+Pl+Pass' => ['patiebamur'],
        '+2nd+Pl+Pass' => ['patiebamini'],
        '+3rd+Pl+Pass' => ['patiebantur'],
    },
    '+Impf+Subj' => {
        '+1st+Sg+Pass' => ['paterer'],
        '+2nd+Sg+Pass' => ['patereris', 'paterere'],
        '+3rd+Sg+Pass' => ['pateretur'],
        '+1st+Pl+Pass' => ['pateremur'],
        '+2nd+Pl+Pass' => ['pateremini'],
        '+3rd+Pl+Pass' => ['paterentur'],
    },
    '+Fut+Ind' => {
        '+1st+Sg+Pass' => ['patiar'],
        '+2nd+Sg+Pass' => ['patieris', 'patiere'],
        '+3rd+Sg+Pass' => ['patietur'],
        '+1st+Pl+Pass' => ['patiemur'],
        '+2nd+Pl+Pass' => ['patiemini'],
        '+3rd+Pl+Pass' => ['patientur'],
    },
    '+Pres+Impv' => {
        '+2nd+Sg+Pass' => ['patere'],
        '+2nd+Pl+Pass' => ['patimini'],
    },
    '+Inf' => {
        '+Pres+Pass' => ['pati'],
    },
    '+Part' => {
        '+Pres' => {
            '+Masc' => {
                '+Nom+Sg' => ['patiens'],
                '+Voc+Sg' => ['patiens'],
                '+Acc+Sg' => ['patientem'],
                '+Gen+Sg' => ['patientis'],
                '+Dat+Sg' => ['patienti'],
                '+Abl+Sg' => ['patienti', 'patiente'],

                '+Nom+Pl' => ['patientes'],
                '+Voc+Pl' => ['patientes'],
                '+Acc+Pl' => ['patientes'],
                '+Gen+Pl' => ['patientium'],
                '+Dat+Pl' => ['patientibus'],
                '+Abl+Pl' => ['patientibus'],
            },
            '+Fem' => {
                '+Nom+Sg' => ['patiens'],
                '+Voc+Sg' => ['patiens'],
                '+Acc+Sg' => ['patientem'],
                '+Gen+Sg' => ['patientis'],
                '+Dat+Sg' => ['patienti'],
                '+Abl+Sg' => ['patienti', 'patiente'],

                '+Nom+Pl' => ['patientes'],
                '+Voc+Pl' => ['patientes'],
                '+Acc+Pl' => ['patientes'],
                '+Gen+Pl' => ['patientium'],
                '+Dat+Pl' => ['patientibus'],
                '+Abl+Pl' => ['patientibus'],
            },
            '+Neut' => {
                '+Nom+Sg' => ['patiens'],
                '+Voc+Sg' => ['patiens'],
                '+Acc+Sg' => ['patiens'],
                '+Gen+Sg' => ['patientis'],
                '+Dat+Sg' => ['patienti'],
                '+Abl+Sg' => ['patienti', 'patiente'],

                '+Nom+Pl' => ['patientia'],
                '+Voc+Pl' => ['patientia'],
                '+Acc+Pl' => ['patientia'],
                '+Gen+Pl' => ['patientium'],
                '+Dat+Pl' => ['patientibus'],
                '+Abl+Pl' => ['patientibus'],
            },
        },
        '+Perf' => {
            '+Masc' => {
                '+Nom+Sg' => ['passus'],
                '+Voc+Sg' => ['passe'],
                '+Acc+Sg' => ['passum'],
                '+Gen+Sg' => ['passi'],
                '+Dat+Sg' => ['passo'],
                '+Abl+Sg' => ['passo'],

                '+Nom+Pl' => ['passi'],
                '+Voc+Pl' => ['passi'],
                '+Acc+Pl' => ['passos'],
                '+Gen+Pl' => ['passorum'],
                '+Dat+Pl' => ['passis'],
                '+Abl+Pl' => ['passis'],
            },
            '+Fem' => {
                '+Nom+Sg' => ['passa'],
                '+Voc+Sg' => ['passa'],
                '+Acc+Sg' => ['passam'],
                '+Gen+Sg' => ['passae'],
                '+Dat+Sg' => ['passae'],
                '+Abl+Sg' => ['passa'],

                '+Nom+Pl' => ['passae'],
                '+Voc+Pl' => ['passae'],
                '+Acc+Pl' => ['passas'],
                '+Gen+Pl' => ['passarum'],
                '+Dat+Pl' => ['passis'],
                '+Abl+Pl' => ['passis'],
            },
            '+Neut' => {
                '+Nom+Sg' => ['passum'],
                '+Voc+Sg' => ['passum'],
                '+Acc+Sg' => ['passum'],
                '+Gen+Sg' => ['passi'],
                '+Dat+Sg' => ['passo'],
                '+Abl+Sg' => ['passo'],

                '+Nom+Pl' => ['passa'],
                '+Voc+Pl' => ['passa'],
                '+Acc+Pl' => ['passa'],
                '+Gen+Pl' => ['passorum'],
                '+Dat+Pl' => ['passis'],
                '+Abl+Pl' => ['passis'],
            },
        },
        '+Fut' => {
            '+Masc' => {
                '+Nom+Sg' => ['passurus'],
                '+Voc+Sg' => ['passure'],
                '+Acc+Sg' => ['passurum'],
                '+Gen+Sg' => ['passuri'],
                '+Dat+Sg' => ['passuro'],
                '+Abl+Sg' => ['passuro'],

                '+Nom+Pl' => ['passuri'],
                '+Voc+Pl' => ['passuri'],
                '+Acc+Pl' => ['passuros'],
                '+Gen+Pl' => ['passurorum'],
                '+Dat+Pl' => ['passuris'],
                '+Abl+Pl' => ['passuris'],
            },
            '+Fem' => {
                '+Nom+Sg' => ['passura'],
                '+Voc+Sg' => ['passura'],
                '+Acc+Sg' => ['passuram'],
                '+Gen+Sg' => ['passurae'],
                '+Dat+Sg' => ['passurae'],
                '+Abl+Sg' => ['passura'],

                '+Nom+Pl' => ['passurae'],
                '+Voc+Pl' => ['passurae'],
                '+Acc+Pl' => ['passuras'],
                '+Gen+Pl' => ['passurarum'],
                '+Dat+Pl' => ['passuris'],
                '+Abl+Pl' => ['passuris'],
            },
            '+Neut' => {
                '+Nom+Sg' => ['passurum'],
                '+Voc+Sg' => ['passurum'],
                '+Acc+Sg' => ['passurum'],
                '+Gen+Sg' => ['passuri'],
                '+Dat+Sg' => ['passuro'],
                '+Abl+Sg' => ['passuro'],

                '+Nom+Pl' => ['passura'],
                '+Voc+Pl' => ['passura'],
                '+Acc+Pl' => ['passura'],
                '+Gen+Pl' => ['passurorum'],
                '+Dat+Pl' => ['passuris'],
                '+Abl+Pl' => ['passuris'],
            },
        },
    },
    '+Ger' => {
        '+Acc' => ['patiendum'],
        '+Gen' => ['patiendi'],
        '+Dat' => ['patiendo'],
        '+Abl' => ['patiendo'],
    },
    '+Gerv' => {
        '+Masc' => {
            '+Nom+Sg' => ['patiendus'],
            '+Voc+Sg' => ['patiende'],
            '+Acc+Sg' => ['patiendum'],
            '+Gen+Sg' => ['patiendi'],
            '+Dat+Sg' => ['patiendo'],
            '+Abl+Sg' => ['patiendo'],

            '+Nom+Pl' => ['patiendi'],
            '+Voc+Pl' => ['patiendi'],
            '+Acc+Pl' => ['patiendos'],
            '+Gen+Pl' => ['patiendorum'],
            '+Dat+Pl' => ['patiendis'],
            '+Abl+Pl' => ['patiendis'],
        },
        '+Fem' => {
            '+Nom+Sg' => ['patienda'],
            '+Voc+Sg' => ['patienda'],
            '+Acc+Sg' => ['patiendam'],
            '+Gen+Sg' => ['patiendae'],
            '+Dat+Sg' => ['patiendae'],
            '+Abl+Sg' => ['patienda'],

            '+Nom+Pl' => ['patiendae'],
            '+Voc+Pl' => ['patiendae'],
            '+Acc+Pl' => ['patiendas'],
            '+Gen+Pl' => ['patiendarum'],
            '+Dat+Pl' => ['patiendis'],
            '+Abl+Pl' => ['patiendis'],
        },
        '+Neut' => {
            '+Nom+Sg' => ['patiendum'],
            '+Voc+Sg' => ['patiendum'],
            '+Acc+Sg' => ['patiendum'],
            '+Gen+Sg' => ['patiendi'],
            '+Dat+Sg' => ['patiendo'],
            '+Abl+Sg' => ['patiendo'],

            '+Nom+Pl' => ['patienda'],
            '+Voc+Pl' => ['patienda'],
            '+Acc+Pl' => ['patienda'],
            '+Gen+Pl' => ['patiendorum'],
            '+Dat+Pl' => ['patiendis'],
            '+Abl+Pl' => ['patiendis'],
        },
    },
    '+SupI' => ['passum'],
    '+SupII' => ['passu'],
});
