use Morph;
use Test::More;

plan(tests => 511);

test_hash('moneo+Verb', {
    '+Pres+Ind' => {
        '+1st+Sg+Act' => ['moneo'],
        '+2nd+Sg+Act' => ['mones'],
        '+3rd+Sg+Act' => ['monet'],
        '+1st+Pl+Act' => ['monemus'],
        '+2nd+Pl+Act' => ['monetis'],
        '+3rd+Pl+Act' => ['monent'],
        '+1st+Sg+Pass' => ['moneor'],
        '+2nd+Sg+Pass' => ['moneris', 'monere'],
        '+3rd+Sg+Pass' => ['monetur'],
        '+1st+Pl+Pass' => ['monemur'],
        '+2nd+Pl+Pass' => ['monemini'],
        '+3rd+Pl+Pass' => ['monentur'],
    },
    '+Pres+Subj' => {
        '+1st+Sg+Act' => ['moneam'],
        '+2nd+Sg+Act' => ['moneas'],
        '+3rd+Sg+Act' => ['moneat'],
        '+1st+Pl+Act' => ['moneamus'],
        '+2nd+Pl+Act' => ['moneatis'],
        '+3rd+Pl+Act' => ['moneant'],
        '+1st+Sg+Pass' => ['monear'],
        '+2nd+Sg+Pass' => ['monearis', 'moneare'],
        '+3rd+Sg+Pass' => ['moneatur'],
        '+1st+Pl+Pass' => ['moneamur'],
        '+2nd+Pl+Pass' => ['moneamini'],
        '+3rd+Pl+Pass' => ['moneantur'],
    },
    '+Impf+Ind' => {
        '+1st+Sg+Act' => ['monebam'],
        '+2nd+Sg+Act' => ['monebas'],
        '+3rd+Sg+Act' => ['monebat'],
        '+1st+Pl+Act' => ['monebamus'],
        '+2nd+Pl+Act' => ['monebatis'],
        '+3rd+Pl+Act' => ['monebant'],
        '+1st+Sg+Pass' => ['monebar'],
        '+2nd+Sg+Pass' => ['monebaris', 'monebare'],
        '+3rd+Sg+Pass' => ['monebatur'],
        '+1st+Pl+Pass' => ['monebamur'],
        '+2nd+Pl+Pass' => ['monebamini'],
        '+3rd+Pl+Pass' => ['monebantur'],
    },
    '+Impf+Subj' => {
        '+1st+Sg+Act' => ['monerem'],
        '+2nd+Sg+Act' => ['moneres'],
        '+3rd+Sg+Act' => ['moneret'],
        '+1st+Pl+Act' => ['moneremus'],
        '+2nd+Pl+Act' => ['moneretis'],
        '+3rd+Pl+Act' => ['monerent'],
        '+1st+Sg+Pass' => ['monerer'],
        '+2nd+Sg+Pass' => ['monereris', 'monerere'],
        '+3rd+Sg+Pass' => ['moneretur'],
        '+1st+Pl+Pass' => ['moneremur'],
        '+2nd+Pl+Pass' => ['moneremini'],
        '+3rd+Pl+Pass' => ['monerentur'],
    },
    '+Fut+Ind' => {
        '+1st+Sg+Act' => ['monebo'],
        '+2nd+Sg+Act' => ['monebis'],
        '+3rd+Sg+Act' => ['monebit'],
        '+1st+Pl+Act' => ['monebimus'],
        '+2nd+Pl+Act' => ['monebitis'],
        '+3rd+Pl+Act' => ['monebunt'],
        '+1st+Sg+Pass' => ['monebor'],
        '+2nd+Sg+Pass' => ['moneberis', 'monebere'],
        '+3rd+Sg+Pass' => ['monebitur'],
        '+1st+Pl+Pass' => ['monebimur'],
        '+2nd+Pl+Pass' => ['monebimini'],
        '+3rd+Pl+Pass' => ['monebuntur'],
    },
    '+Perf+Ind' => {
        '+1st+Sg+Act' => ['monui'],
        '+2nd+Sg+Act' => ['monuisti'],
        '+3rd+Sg+Act' => ['monuit'],
        '+1st+Pl+Act' => ['monuimus'],
        '+2nd+Pl+Act' => ['monuistis'],
        '+3rd+Pl+Act' => ['monuerunt', 'monuere'],
    },
    '+Perf+Subj' => {
        '+1st+Sg+Act' => ['monuerim'],
        '+2nd+Sg+Act' => ['monueris'],
        '+3rd+Sg+Act' => ['monuerit'],
        '+1st+Pl+Act' => ['monuerimus'],
        '+2nd+Pl+Act' => ['monueritis'],
        '+3rd+Pl+Act' => ['monuerint'],
    },
    '+Pqp+Ind' => {
        '+1st+Sg+Act' => ['monueram'],
        '+2nd+Sg+Act' => ['monueras'],
        '+3rd+Sg+Act' => ['monuerat'],
        '+1st+Pl+Act' => ['monueramus'],
        '+2nd+Pl+Act' => ['monueratis'],
        '+3rd+Pl+Act' => ['monuerant'],
    },
    '+Pqp+Subj' => {
        '+1st+Sg+Act' => ['monuissem'],
        '+2nd+Sg+Act' => ['monuisses'],
        '+3rd+Sg+Act' => ['monuisset'],
        '+1st+Pl+Act' => ['monuissemus'],
        '+2nd+Pl+Act' => ['monuissetis'],
        '+3rd+Pl+Act' => ['monuissent'],
    },
    '+FutII+Ind' => {
        '+1st+Sg+Act' => ['monuero'],
        '+2nd+Sg+Act' => ['monueris'],
        '+3rd+Sg+Act' => ['monuerit'],
        '+1st+Pl+Act' => ['monuerimus'],
        '+2nd+Pl+Act' => ['monueritis'],
        '+3rd+Pl+Act' => ['monuerint'],
    },
    '+Pres+Impv' => {
        '+2nd+Sg+Act'  => ['mone'],
        '+2nd+Pl+Act'  => ['monete'],
        '+2nd+Sg+Pass' => ['monere'],
        '+2nd+Pl+Pass' => ['monemini'],
    },
    '+Fut+Impv' => {
        '+2nd+Sg+Act' => ['moneto'],
        '+3rd+Sg+Act' => ['moneto'],
        '+2nd+Pl+Act' => ['monetote'],
        '+3rd+Pl+Act' => ['monento'],
    },
    '+Inf' => {
        '+Pres+Act' => ['monere'],
        '+Pres+Pass' => ['moneri'],
        '+Perf+Act' => ['monuisse'],
    },
    '+Part' => {
        '+Pres' => {
            '+Masc' => {
                '+Nom+Sg' => ['monens'],
                '+Voc+Sg' => ['monens'],
                '+Acc+Sg' => ['monentem'],
                '+Gen+Sg' => ['monentis'],
                '+Dat+Sg' => ['monenti'],
                '+Abl+Sg' => ['monenti', 'monente'],

                '+Nom+Pl' => ['monentes'],
                '+Voc+Pl' => ['monentes'],
                '+Acc+Pl' => ['monentes'],
                '+Gen+Pl' => ['monentium'],
                '+Dat+Pl' => ['monentibus'],
                '+Abl+Pl' => ['monentibus'],
            },
            '+Fem' => {
                '+Nom+Sg' => ['monens'],
                '+Voc+Sg' => ['monens'],
                '+Acc+Sg' => ['monentem'],
                '+Gen+Sg' => ['monentis'],
                '+Dat+Sg' => ['monenti'],
                '+Abl+Sg' => ['monenti', 'monente'],

                '+Nom+Pl' => ['monentes'],
                '+Voc+Pl' => ['monentes'],
                '+Acc+Pl' => ['monentes'],
                '+Gen+Pl' => ['monentium'],
                '+Dat+Pl' => ['monentibus'],
                '+Abl+Pl' => ['monentibus'],
            },
            '+Neut' => {
                '+Nom+Sg' => ['monens'],
                '+Voc+Sg' => ['monens'],
                '+Acc+Sg' => ['monens'],
                '+Gen+Sg' => ['monentis'],
                '+Dat+Sg' => ['monenti'],
                '+Abl+Sg' => ['monenti', 'monente'],

                '+Nom+Pl' => ['monentia'],
                '+Voc+Pl' => ['monentia'],
                '+Acc+Pl' => ['monentia'],
                '+Gen+Pl' => ['monentium'],
                '+Dat+Pl' => ['monentibus'],
                '+Abl+Pl' => ['monentibus'],
            },
        },
        '+Perf' => {
            '+Masc' => {
                '+Nom+Sg' => ['monitus'],
                '+Voc+Sg' => ['monite'],
                '+Acc+Sg' => ['monitum'],
                '+Gen+Sg' => ['moniti'],
                '+Dat+Sg' => ['monito'],
                '+Abl+Sg' => ['monito'],

                '+Nom+Pl' => ['moniti'],
                '+Voc+Pl' => ['moniti'],
                '+Acc+Pl' => ['monitos'],
                '+Gen+Pl' => ['monitorum'],
                '+Dat+Pl' => ['monitis'],
                '+Abl+Pl' => ['monitis'],
            },
            '+Fem' => {
                '+Nom+Sg' => ['monita'],
                '+Voc+Sg' => ['monita'],
                '+Acc+Sg' => ['monitam'],
                '+Gen+Sg' => ['monitae'],
                '+Dat+Sg' => ['monitae'],
                '+Abl+Sg' => ['monita'],

                '+Nom+Pl' => ['monitae'],
                '+Voc+Pl' => ['monitae'],
                '+Acc+Pl' => ['monitas'],
                '+Gen+Pl' => ['monitarum'],
                '+Dat+Pl' => ['monitis'],
                '+Abl+Pl' => ['monitis'],
            },
            '+Neut' => {
                '+Nom+Sg' => ['monitum'],
                '+Voc+Sg' => ['monitum'],
                '+Acc+Sg' => ['monitum'],
                '+Gen+Sg' => ['moniti'],
                '+Dat+Sg' => ['monito'],
                '+Abl+Sg' => ['monito'],

                '+Nom+Pl' => ['monita'],
                '+Voc+Pl' => ['monita'],
                '+Acc+Pl' => ['monita'],
                '+Gen+Pl' => ['monitorum'],
                '+Dat+Pl' => ['monitis'],
                '+Abl+Pl' => ['monitis'],
            },
        },
        '+Fut' => {
            '+Masc' => {
                '+Nom+Sg' => ['moniturus'],
                '+Voc+Sg' => ['moniture'],
                '+Acc+Sg' => ['moniturum'],
                '+Gen+Sg' => ['monituri'],
                '+Dat+Sg' => ['monituro'],
                '+Abl+Sg' => ['monituro'],

                '+Nom+Pl' => ['monituri'],
                '+Voc+Pl' => ['monituri'],
                '+Acc+Pl' => ['monituros'],
                '+Gen+Pl' => ['moniturorum'],
                '+Dat+Pl' => ['monituris'],
                '+Abl+Pl' => ['monituris'],
            },
            '+Fem' => {
                '+Nom+Sg' => ['monitura'],
                '+Voc+Sg' => ['monitura'],
                '+Acc+Sg' => ['monituram'],
                '+Gen+Sg' => ['moniturae'],
                '+Dat+Sg' => ['moniturae'],
                '+Abl+Sg' => ['monitura'],

                '+Nom+Pl' => ['moniturae'],
                '+Voc+Pl' => ['moniturae'],
                '+Acc+Pl' => ['monituras'],
                '+Gen+Pl' => ['moniturarum'],
                '+Dat+Pl' => ['monituris'],
                '+Abl+Pl' => ['monituris'],
            },
            '+Neut' => {
                '+Nom+Sg' => ['moniturum'],
                '+Voc+Sg' => ['moniturum'],
                '+Acc+Sg' => ['moniturum'],
                '+Gen+Sg' => ['monituri'],
                '+Dat+Sg' => ['monituro'],
                '+Abl+Sg' => ['monituro'],

                '+Nom+Pl' => ['monitura'],
                '+Voc+Pl' => ['monitura'],
                '+Acc+Pl' => ['monitura'],
                '+Gen+Pl' => ['moniturorum'],
                '+Dat+Pl' => ['monituris'],
                '+Abl+Pl' => ['monituris'],
            },
        },
    },
    '+Ger' => {
        '+Acc' => ['monendum'],
        '+Gen' => ['monendi'],
        '+Dat' => ['monendo'],
        '+Abl' => ['monendo'],
    },
    '+Gerv' => {
        '+Masc' => {
            '+Nom+Sg' => ['monendus'],
            '+Voc+Sg' => ['monende'],
            '+Acc+Sg' => ['monendum'],
            '+Gen+Sg' => ['monendi'],
            '+Dat+Sg' => ['monendo'],
            '+Abl+Sg' => ['monendo'],

            '+Nom+Pl' => ['monendi'],
            '+Voc+Pl' => ['monendi'],
            '+Acc+Pl' => ['monendos'],
            '+Gen+Pl' => ['monendorum'],
            '+Dat+Pl' => ['monendis'],
            '+Abl+Pl' => ['monendis'],
        },
        '+Fem' => {
            '+Nom+Sg' => ['monenda'],
            '+Voc+Sg' => ['monenda'],
            '+Acc+Sg' => ['monendam'],
            '+Gen+Sg' => ['monendae'],
            '+Dat+Sg' => ['monendae'],
            '+Abl+Sg' => ['monenda'],

            '+Nom+Pl' => ['monendae'],
            '+Voc+Pl' => ['monendae'],
            '+Acc+Pl' => ['monendas'],
            '+Gen+Pl' => ['monendarum'],
            '+Dat+Pl' => ['monendis'],
            '+Abl+Pl' => ['monendis'],
        },
        '+Neut' => {
            '+Nom+Sg' => ['monendum'],
            '+Voc+Sg' => ['monendum'],
            '+Acc+Sg' => ['monendum'],
            '+Gen+Sg' => ['monendi'],
            '+Dat+Sg' => ['monendo'],
            '+Abl+Sg' => ['monendo'],

            '+Nom+Pl' => ['monenda'],
            '+Voc+Pl' => ['monenda'],
            '+Acc+Pl' => ['monenda'],
            '+Gen+Pl' => ['monendorum'],
            '+Dat+Pl' => ['monendis'],
            '+Abl+Pl' => ['monendis'],
        },
    },
    '+SupI' => ['monitum'],
    '+SupII' => ['monitu'],
});
