#!/usr/bin/env python

from morph import *
from TAP.Simple import *

plan(374)

test_hash('hortor+Verb+Dep', {
    '+Pres+Ind': {
        '+1S+Pass': ['hortor'],
        '+2S+Pass': ['hortaris', 'hortare'],
        '+3S+Pass': ['hortatur'],
        '+1P+Pass': ['hortamur'],
        '+2P+Pass': ['hortamini'],
        '+3P+Pass': ['hortantur'],
    },
    '+Pres+Subj': {
        '+1S+Pass': ['horter'],
        '+2S+Pass': ['horteris', 'hortere'],
        '+3S+Pass': ['hortetur'],
        '+1P+Pass': ['hortemur'],
        '+2P+Pass': ['hortemini'],
        '+3P+Pass': ['hortentur'],
    },
    '+Impf+Ind': {
        '+1S+Pass': ['hortabar'],
        '+2S+Pass': ['hortabaris', 'hortabare'],
        '+3S+Pass': ['hortabatur'],
        '+1P+Pass': ['hortabamur'],
        '+2P+Pass': ['hortabamini'],
        '+3P+Pass': ['hortabantur'],
    },
    '+Impf+Subj': {
        '+1S+Pass': ['hortarer'],
        '+2S+Pass': ['hortareris', 'hortarere'],
        '+3S+Pass': ['hortaretur'],
        '+1P+Pass': ['hortaremur'],
        '+2P+Pass': ['hortaremini'],
        '+3P+Pass': ['hortarentur'],
    },
    '+Fut+Ind': {
        '+1S+Pass': ['hortabor'],
        '+2S+Pass': ['hortaberis', 'hortabere'],
        '+3S+Pass': ['hortabitur'],
        '+1P+Pass': ['hortabimur'],
        '+2P+Pass': ['hortabimini'],
        '+3P+Pass': ['hortabuntur'],
    },
    '+Pres+Impv': {
        '+2S+Pass': ['hortare'],
        '+2P+Pass': ['hortamini'],
    },
    '+Inf': {
        '+Pres+Pass': ['hortari'],
    },
    '+Part': {
        '+Pres': {
            '+Masc': {
                '+Nom+Sg': ['hortans'],
                '+Voc+Sg': ['hortans'],
                '+Acc+Sg': ['hortantem'],
                '+Gen+Sg': ['hortantis'],
                '+Dat+Sg': ['hortanti'],
                '+Abl+Sg': ['hortanti', 'hortante'],

                '+Nom+Pl': ['hortantes'],
                '+Voc+Pl': ['hortantes'],
                '+Acc+Pl': ['hortantes'],
                '+Gen+Pl': ['hortantium'],
                '+Dat+Pl': ['hortantibus'],
                '+Abl+Pl': ['hortantibus'],
            },
            '+Fem': {
                '+Nom+Sg': ['hortans'],
                '+Voc+Sg': ['hortans'],
                '+Acc+Sg': ['hortantem'],
                '+Gen+Sg': ['hortantis'],
                '+Dat+Sg': ['hortanti'],
                '+Abl+Sg': ['hortanti', 'hortante'],

                '+Nom+Pl': ['hortantes'],
                '+Voc+Pl': ['hortantes'],
                '+Acc+Pl': ['hortantes'],
                '+Gen+Pl': ['hortantium'],
                '+Dat+Pl': ['hortantibus'],
                '+Abl+Pl': ['hortantibus'],
            },
            '+Neut': {
                '+Nom+Sg': ['hortans'],
                '+Voc+Sg': ['hortans'],
                '+Acc+Sg': ['hortans'],
                '+Gen+Sg': ['hortantis'],
                '+Dat+Sg': ['hortanti'],
                '+Abl+Sg': ['hortanti', 'hortante'],

                '+Nom+Pl': ['hortantia'],
                '+Voc+Pl': ['hortantia'],
                '+Acc+Pl': ['hortantia'],
                '+Gen+Pl': ['hortantium'],
                '+Dat+Pl': ['hortantibus'],
                '+Abl+Pl': ['hortantibus'],
            },
        },
        '+Perf': {
            '+Masc': {
                '+Nom+Sg': ['hortatus'],
                '+Voc+Sg': ['hortate'],
                '+Acc+Sg': ['hortatum'],
                '+Gen+Sg': ['hortati'],
                '+Dat+Sg': ['hortato'],
                '+Abl+Sg': ['hortato'],

                '+Nom+Pl': ['hortati'],
                '+Voc+Pl': ['hortati'],
                '+Acc+Pl': ['hortatos'],
                '+Gen+Pl': ['hortatorum'],
                '+Dat+Pl': ['hortatis'],
                '+Abl+Pl': ['hortatis'],
            },
            '+Fem': {
                '+Nom+Sg': ['hortata'],
                '+Voc+Sg': ['hortata'],
                '+Acc+Sg': ['hortatam'],
                '+Gen+Sg': ['hortatae'],
                '+Dat+Sg': ['hortatae'],
                '+Abl+Sg': ['hortata'],

                '+Nom+Pl': ['hortatae'],
                '+Voc+Pl': ['hortatae'],
                '+Acc+Pl': ['hortatas'],
                '+Gen+Pl': ['hortatarum'],
                '+Dat+Pl': ['hortatis'],
                '+Abl+Pl': ['hortatis'],
            },
            '+Neut': {
                '+Nom+Sg': ['hortatum'],
                '+Voc+Sg': ['hortatum'],
                '+Acc+Sg': ['hortatum'],
                '+Gen+Sg': ['hortati'],
                '+Dat+Sg': ['hortato'],
                '+Abl+Sg': ['hortato'],

                '+Nom+Pl': ['hortata'],
                '+Voc+Pl': ['hortata'],
                '+Acc+Pl': ['hortata'],
                '+Gen+Pl': ['hortatorum'],
                '+Dat+Pl': ['hortatis'],
                '+Abl+Pl': ['hortatis'],
            },
        },
        '+Fut': {
            '+Masc': {
                '+Nom+Sg': ['hortaturus'],
                '+Voc+Sg': ['hortature'],
                '+Acc+Sg': ['hortaturum'],
                '+Gen+Sg': ['hortaturi'],
                '+Dat+Sg': ['hortaturo'],
                '+Abl+Sg': ['hortaturo'],

                '+Nom+Pl': ['hortaturi'],
                '+Voc+Pl': ['hortaturi'],
                '+Acc+Pl': ['hortaturos'],
                '+Gen+Pl': ['hortaturorum'],
                '+Dat+Pl': ['hortaturis'],
                '+Abl+Pl': ['hortaturis'],
            },
            '+Fem': {
                '+Nom+Sg': ['hortatura'],
                '+Voc+Sg': ['hortatura'],
                '+Acc+Sg': ['hortaturam'],
                '+Gen+Sg': ['hortaturae'],
                '+Dat+Sg': ['hortaturae'],
                '+Abl+Sg': ['hortatura'],

                '+Nom+Pl': ['hortaturae'],
                '+Voc+Pl': ['hortaturae'],
                '+Acc+Pl': ['hortaturas'],
                '+Gen+Pl': ['hortaturarum'],
                '+Dat+Pl': ['hortaturis'],
                '+Abl+Pl': ['hortaturis'],
            },
            '+Neut': {
                '+Nom+Sg': ['hortaturum'],
                '+Voc+Sg': ['hortaturum'],
                '+Acc+Sg': ['hortaturum'],
                '+Gen+Sg': ['hortaturi'],
                '+Dat+Sg': ['hortaturo'],
                '+Abl+Sg': ['hortaturo'],

                '+Nom+Pl': ['hortatura'],
                '+Voc+Pl': ['hortatura'],
                '+Acc+Pl': ['hortatura'],
                '+Gen+Pl': ['hortaturorum'],
                '+Dat+Pl': ['hortaturis'],
                '+Abl+Pl': ['hortaturis'],
            },
        },
    },
    '+Ger': {
        '+Acc': ['hortandum'],
        '+Gen': ['hortandi'],
        '+Dat': ['hortando'],
        '+Abl': ['hortando'],
    },
    '+Gerv': {
        '+Masc': {
            '+Nom+Sg': ['hortandus'],
            '+Voc+Sg': ['hortande'],
            '+Acc+Sg': ['hortandum'],
            '+Gen+Sg': ['hortandi'],
            '+Dat+Sg': ['hortando'],
            '+Abl+Sg': ['hortando'],

            '+Nom+Pl': ['hortandi'],
            '+Voc+Pl': ['hortandi'],
            '+Acc+Pl': ['hortandos'],
            '+Gen+Pl': ['hortandorum'],
            '+Dat+Pl': ['hortandis'],
            '+Abl+Pl': ['hortandis'],
        },
        '+Fem': {
            '+Nom+Sg': ['hortanda'],
            '+Voc+Sg': ['hortanda'],
            '+Acc+Sg': ['hortandam'],
            '+Gen+Sg': ['hortandae'],
            '+Dat+Sg': ['hortandae'],
            '+Abl+Sg': ['hortanda'],

            '+Nom+Pl': ['hortandae'],
            '+Voc+Pl': ['hortandae'],
            '+Acc+Pl': ['hortandas'],
            '+Gen+Pl': ['hortandarum'],
            '+Dat+Pl': ['hortandis'],
            '+Abl+Pl': ['hortandis'],
        },
        '+Neut': {
            '+Nom+Sg': ['hortandum'],
            '+Voc+Sg': ['hortandum'],
            '+Acc+Sg': ['hortandum'],
            '+Gen+Sg': ['hortandi'],
            '+Dat+Sg': ['hortando'],
            '+Abl+Sg': ['hortando'],

            '+Nom+Pl': ['hortanda'],
            '+Voc+Pl': ['hortanda'],
            '+Acc+Pl': ['hortanda'],
            '+Gen+Pl': ['hortandorum'],
            '+Dat+Pl': ['hortandis'],
            '+Abl+Pl': ['hortandis'],
        },
    },
    '+SupI': ['hortatum'],
    '+SupII': ['hortatu'],
})
diag("%d" % Morph.formcount)
