#!/usr/bin/python

from morph import *
from TAP.Simple import *

plan(208)

test_hash('capio+Verb', {
    '+Pres+Ind': {
        '+1S+Act': ['capio'],
        '+2S+Act': ['capis'],
        '+3S+Act': ['capit'],
        '+1P+Act': ['capimus'],
        '+2P+Act': ['capitis'],
        '+3P+Act': ['capiunt'],
        '+1S+Pass': ['capior'],
        '+2S+Pass': ['caperis', 'capere'],
        '+3S+Pass': ['capitur'],
        '+1P+Pass': ['capimur'],
        '+2P+Pass': ['capimini'],
        '+3P+Pass': ['capiuntur'],
    },
    '+Pres+Subj': {
        '+1S+Act': ['capiam'],
        '+2S+Act': ['capias'],
        '+3S+Act': ['capiat'],
        '+1P+Act': ['capiamus'],
        '+2P+Act': ['capiatis'],
        '+3P+Act': ['capiant'],
        '+1S+Pass': ['capiar'],
        '+2S+Pass': ['capiaris', 'capiare'],
        '+3S+Pass': ['capiatur'],
        '+1P+Pass': ['capiamur'],
        '+2P+Pass': ['capiamini'],
        '+3P+Pass': ['capiantur'],
    },
    '+Impf+Ind': {
        '+1S+Act': ['capiebam'],
        '+2S+Act': ['capiebas'],
        '+3S+Act': ['capiebat'],
        '+1P+Act': ['capiebamus'],
        '+2P+Act': ['capiebatis'],
        '+3P+Act': ['capiebant'],
        '+1S+Pass': ['capiebar'],
        '+2S+Pass': ['capiebaris', 'capiebare'],
        '+3S+Pass': ['capiebatur'],
        '+1P+Pass': ['capiebamur'],
        '+2P+Pass': ['capiebamini'],
        '+3P+Pass': ['capiebantur'],
    },
    '+Impf+Subj': {
        '+1S+Act': ['caperem'],
        '+2S+Act': ['caperes'],
        '+3S+Act': ['caperet'],
        '+1P+Act': ['caperemus'],
        '+2P+Act': ['caperetis'],
        '+3P+Act': ['caperent'],
        '+1S+Pass': ['caperer'],
        '+2S+Pass': ['capereris', 'caperere'],
        '+3S+Pass': ['caperetur'],
        '+1P+Pass': ['caperemur'],
        '+2P+Pass': ['caperemini'],
        '+3P+Pass': ['caperentur'],
    },
    '+Fut+Ind': {
        '+1S+Act': ['capiam'],
        '+2S+Act': ['capies'],
        '+3S+Act': ['capiet'],
        '+1P+Act': ['capiemus'],
        '+2P+Act': ['capietis'],
        '+3P+Act': ['capient'],
        '+1S+Pass': ['capiar'],
        '+2S+Pass': ['capieris', 'capiere'],
        '+3S+Pass': ['capietur'],
        '+1P+Pass': ['capiemur'],
        '+2P+Pass': ['capiemini'],
        '+3P+Pass': ['capientur'],
    },
    '+Perf+Ind': {
        '+1S+Act': ['cepi'],
        '+2S+Act': ['cepisti'],
        '+3S+Act': ['cepit'],
        '+1P+Act': ['cepimus'],
        '+2P+Act': ['cepistis'],
        '+3P+Act': ['ceperunt', 'cepere'],
    },
    '+Perf+Subj': {
        '+1S+Act': ['ceperim'],
        '+2S+Act': ['ceperis'],
        '+3S+Act': ['ceperit'],
        '+1P+Act': ['ceperimus'],
        '+2P+Act': ['ceperitis'],
        '+3P+Act': ['ceperint'],
    },
    '+Pqp+Ind': {
        '+1S+Act': ['ceperam'],
        '+2S+Act': ['ceperas'],
        '+3S+Act': ['ceperat'],
        '+1P+Act': ['ceperamus'],
        '+2P+Act': ['ceperatis'],
        '+3P+Act': ['ceperant'],
    },
    '+Pqp+Subj': {
        '+1S+Act': ['cepissem'],
        '+2S+Act': ['cepisses'],
        '+3S+Act': ['cepisset'],
        '+1P+Act': ['cepissemus'],
        '+2P+Act': ['cepissetis'],
        '+3P+Act': ['cepissent'],
    },
    '+FutII+Ind': {
        '+1S+Act': ['cepero'],
        '+2S+Act': ['ceperis'],
        '+3S+Act': ['ceperit'],
        '+1P+Act': ['ceperimus'],
        '+2P+Act': ['ceperitis'],
        '+3P+Act': ['ceperint'],
    },
    '+Pres+Impv': {
        '+2S+Act' : ['cape'],
        '+2P+Act' : ['capite'],
        '+2S+Pass': ['capere'],
        '+2P+Pass': ['capimini'],
    },
    '+Fut+Impv': {
        '+2S+Act': ['capito'],
        '+3S+Act': ['capito'],
        '+2P+Act': ['capitote'],
        '+3P+Act': ['capiunto'],
    },
    '+Inf': {
        '+Pres+Act': ['capere'],
        '+Pres+Pass': ['capi'],
        '+Perf+Act': ['cepisse'],
    }
})
